"""The world-state store — the ONLY module that speaks SQL (Seam discipline).

Same rule as `providers/`: every database read/write goes through a function
here, and nothing outside this module imports `psycopg` or writes SQL. That keeps
the storage choice swappable (Postgres now; a managed DB or pgvector-enabled
instance later) and the query surface small and logged.

The schema is deliberately minimal but real (PHASE_B_TASKS.md B1):

    canon(id, text, tags)                           — the world's standing facts
    cast(id, name, card_text, logical_voice, tags)  — the DJs (note: "cast" is a
                                                       SQL keyword, always quoted)
    events(id, title, body, in_world_datetime, status, tags, source)
                                                    — dated occurrences; `source`
                                                       is seed (folder) | tick (D3)
    state(key, value)                               — small key/value world state

The canon bible (`docs/canon/`, formerly `docs/CANON.md`) stays the human-editable
source of truth; `world/seed.py` parses it (`world/canon_source.py`) and loads it
here. Connection details come from `settings.database_url` (B0.5) — never a
hardcoded string.

------------------------------------------------------------------------------
Vector search (LIVE as of D2.1; the seam this module reserved in B3 is now built):
pgvector is enabled in `init_schema` and the embeddings live in ONE polymorphic
table — `embeddings(corpus, entity_id, text, source, tags, embedding vector(N))`
— NOT a canon-only table, so D3 (events/stories) and D10 (figures/quotes) reuse it
by passing their own `corpus`. `N` is `settings.embeddings_dim`; the index uses the
COSINE opclass (the chosen model emits L2-normalised vectors). The embedding model
itself lives ONLY behind `providers/embeddings.py`; the vector SQL lives ONLY here
(`insert_embeddings`/`delete_embeddings`/`search`). `entity_id` is a *soft* cross-
table reference (a real FK can't span corpora), so per-entity cleanup is app logic
(`delete_embeddings`), not a cascade. The table is DERIVED/regenerable: re-embedded
on seed, cleared on `reset-world`, not backed up (§2a matrix).
------------------------------------------------------------------------------
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime

import psycopg

from ..config import settings
from ..logging_setup import get_logger

log = get_logger(__name__)


# --- Row shapes (1:1 with the tables) --------------------------------------
# Defined here because they mirror the schema this module owns; the parser
# (canon_source.py) and seed.py import them, so the row shape has one home.


@dataclass(frozen=True)
class CanonFact:
    """One standing world fact (a `canon` row)."""

    id: str
    text: str
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class CastMember:
    """One DJ / presenter (a `cast` row)."""

    id: str
    name: str
    card_text: str
    logical_voice: str
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Event:
    """One dated, progressing occurrence (an `events` row).

    `status` is a stored snapshot (upcoming/today/past) seeded from the bible; B2
    will (re)compute it from `in_world_datetime` relative to the world clock.

    `source` is the row's provenance (`seed` | `tick`): hand-authored from the canon
    folder vs generated by the nightly world tick (D3). It is what lets a canon
    refresh (`seed-canon`) replace only the seed events while the living, tick-
    generated world survives. Folder-loaded events default to `seed`.

    `story_id` + `beat_kind` (D3.0) make an event a *beat of a story*: a story is an
    arced sequence of these dated events (see `Story`). `story_id` is NULL for a
    standalone event (the seeded bible events, which aren't part of a generated arc);
    a tick beat carries its story's id. `beat_kind` is an optional, free-form tag for
    the kind of beat the tick authored it as (e.g. "rumour"/"announcement"/
    "development"/"consequence"/"resolution") — descriptive, not an enforced enum.
    Crucially a beat is STILL just an event with an `in_world_datetime`, so the B2
    clock frames it future/now/past for free — we reuse the events machinery, not
    duplicate it.
    """

    id: str
    title: str
    body: str
    in_world_datetime: datetime
    status: str
    tags: list[str] = field(default_factory=list)
    source: str = "seed"
    story_id: str | None = None
    beat_kind: str | None = None


# An event's provenance (the `events.source` column). A canon refresh replaces only
# SEED rows; TICK rows are the living world the world tick (D3) generates and must
# survive a re-seed. The same split is honoured by D3.0, D10.0 and the §2a matrix.
# The `embeddings.source` column (D2) reuses these SAME values: a canon refresh
# re-embeds the SEED-sourced rows and leaves TICK-sourced embeddings intact.
EVENT_SOURCE_SEED = "seed"
EVENT_SOURCE_TICK = "tick"


# --- Arc stages (D3.0: the narrative lifecycle of a story) ------------------
# Intrinsic domain data (not config — see the config-vs-constant rule in config.py),
# so it lives here next to the schema it governs. These are DISTINCT from
# `events.status_of`'s temporal upcoming/today/past, which is *derived* from a beat's
# datetime vs the world clock. The arc stage is a NARRATIVE property the tick authors
# and advances: a story can be temporally `past` (its latest beat is behind us) yet
# narratively still `developing` (consequences unfolding). Keep the two concepts
# separate — model arc stage explicitly here; derive temporal framing from the date.
ARC_RUMOURED = "rumoured"
ARC_UPCOMING = "upcoming"
ARC_HAPPENING = "happening"
ARC_DEVELOPING = "developing"
ARC_PAST = "past"

# The stages in forward order. `past` is terminal (a resolved story; the tick stops
# advancing it — D3.2 — but it stays in the log forever as history).
ARC_STAGES = (ARC_RUMOURED, ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST)

# Legal transitions: from a stage you may stay put (a new beat, same stage) or jump
# to ANY later stage (a sudden event can leap rumoured -> happening; a false rumour
# can resolve rumoured -> past) — but NEVER move backward, and `past` is terminal
# (no further beats). `advance_story` enforces this via `can_transition`.
ARC_TRANSITIONS: dict[str, tuple[str, ...]] = {
    ARC_RUMOURED: (ARC_RUMOURED, ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_UPCOMING: (ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_HAPPENING: (ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_DEVELOPING: (ARC_DEVELOPING, ARC_PAST),
    ARC_PAST: (),
}


def is_resolved(arc_stage: str) -> bool:
    """True if a story's arc stage is terminal (`past`); the tick stops advancing it."""
    return arc_stage == ARC_PAST


def can_transition(old: str, new: str) -> bool:
    """Whether moving a story from arc stage `old` to `new` is legal (D3.0).

    Forward-or-same only; `past` is terminal. Raises on an unknown stage so a typo in
    the tick fails loudly rather than silently corrupting an arc.
    """
    for stage in (old, new):
        if stage not in ARC_STAGES:
            raise ValueError(
                f"unknown arc stage {stage!r}; expected one of {ARC_STAGES}"
            )
    return new in ARC_TRANSITIONS[old]


@dataclass(frozen=True)
class Story:
    """One arced story — a happening that progresses across ticks (a `stories` row).

    A story is the narrative spine; its individual dated developments are `events`
    rows linked by `story_id` (its *beats*), so each beat is clock-framed for free.
    `arc_stage` is one of `ARC_STAGES`. `source` reuses the EVENT_SOURCE_* split: the
    nightly tick writes `tick` (the living world, survives `seed-canon`); a seeded
    example story (D3.5) would be `seed` (replaced on a canon refresh). `created_tick`
    / `last_advanced_tick` are the monotonic tick counter (the tick owns it) for
    pacing — when the story was born and last moved. `created_at` is real wall-clock
    audit time, filled by the DB default on insert (read-only here).
    """

    id: str
    title: str
    summary: str
    arc_stage: str
    tags: list[str] = field(default_factory=list)
    source: str = EVENT_SOURCE_TICK
    created_tick: int | None = None
    last_advanced_tick: int | None = None
    created_at: datetime | None = None


@dataclass(frozen=True)
class EmbeddingRow:
    """One row to write into the polymorphic `embeddings` table (D2).

    `corpus` is NOT a field — it is the per-batch argument to `insert_embeddings`
    (every row in a batch shares one corpus, e.g. "canon"). `source` is the same
    seed/tick provenance as `events.source` (see EVENT_SOURCE_*). `embedding` is the
    N-float vector; its length MUST equal `settings.embeddings_dim` (the producer
    behind `providers/embeddings.py` validates that — a wrong-dim insert will also
    fail loudly against the `vector(N)` column).
    """

    entity_id: str
    text: str
    source: str
    embedding: list[float]
    tags: list[str] = field(default_factory=list)


# --- Schema -----------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS canon (
    id   text PRIMARY KEY,
    text text NOT NULL,
    tags text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS "cast" (
    id            text PRIMARY KEY,
    name          text NOT NULL,
    card_text     text NOT NULL,
    logical_voice text NOT NULL,
    tags          text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS events (
    id                text PRIMARY KEY,
    title             text NOT NULL,
    body              text NOT NULL,
    in_world_datetime timestamp NOT NULL,
    status            text NOT NULL,
    tags              text[] NOT NULL DEFAULT '{}',
    source            text NOT NULL DEFAULT 'seed'
);

-- The story log (D3.0): arced happenings the nightly tick generates + advances. The
-- beats themselves are `events` rows linked back via `events.story_id` (added in the
-- migrations below) — reuse, not a separate beats table. `source` reuses the
-- seed/tick split (see EVENT_SOURCE_*): tick-owned stories survive a `seed-canon`.
CREATE TABLE IF NOT EXISTS stories (
    id                 text PRIMARY KEY,
    title              text NOT NULL,
    summary            text NOT NULL,
    arc_stage          text NOT NULL,
    tags               text[] NOT NULL DEFAULT '{}',
    source             text NOT NULL DEFAULT 'tick',
    created_tick       integer,
    last_advanced_tick integer,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS state (
    key   text PRIMARY KEY,
    value text NOT NULL
);

-- Indexes for the structured event retrieval B2/B3 lean on (by status, by date).
CREATE INDEX IF NOT EXISTS events_status_idx   ON events (status);
CREATE INDEX IF NOT EXISTS events_datetime_idx ON events (in_world_datetime);
CREATE INDEX IF NOT EXISTS stories_stage_idx   ON stories (arc_stage);
CREATE INDEX IF NOT EXISTS stories_source_idx  ON stories (source);
"""

# Additive, idempotent migrations applied on every `init_schema`, AFTER the schema
# above. This is how a schema change lands once the world is alive: never a
# truncate-reseed (OVERVIEW §2), always `ADD COLUMN IF NOT EXISTS` / a backfill that
# is safe to run repeatedly. On a fresh DB these are no-ops (the column already
# exists from CREATE); on an existing DB they upgrade it in place. The source index
# lives here (not in the schema) so it is only built after the column is guaranteed.
_MIGRATIONS_SQL = """
ALTER TABLE events ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'seed';
CREATE INDEX IF NOT EXISTS events_source_idx ON events (source);

-- D3.0: link an event to its story as a beat (NULL = a standalone, non-arc event).
-- The FK runs `ON DELETE SET NULL` so deleting a story (a full reset) never orphan-
-- errors; the inline REFERENCES needs `stories` to exist first, which the base
-- schema above guarantees (it runs before these migrations). `beat_kind` is an
-- optional free-form descriptor of the beat (see Event docstring).
ALTER TABLE events ADD COLUMN IF NOT EXISTS story_id text
    REFERENCES stories(id) ON DELETE SET NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS beat_kind text;
CREATE INDEX IF NOT EXISTS events_story_idx ON events (story_id);
"""

# The world tables, in a stable order for a single TRUNCATE that reproduces the world
# cleanly on a full reset. `events` references `stories`, but both are truncated in
# one statement so the FK is satisfied. `embeddings` is handled separately (it is
# DERIVED, not source-of-truth world state — see below).
_WORLD_TABLES = ("canon", '"cast"', "events", "stories", "state")

# --- Vector schema (D2.1: pgvector + the ONE polymorphic embeddings table) ---
# Run in init_schema AFTER the base schema. `CREATE EXTENSION vector` needs the
# pgvector system package installed (README documents the Homebrew step) and fails
# LOUDLY if it isn't — the right behaviour, not a silent skip. The table is multi-
# corpus from day one so D3/D10 reuse it (corpus ∈ canon now; event/story/figure/
# quote later). `vector(N)` interpolates `settings.embeddings_dim` (cast to int —
# config, never user input); a later model change means a re-embed + a column
# migration (this CREATE ... IF NOT EXISTS won't resize an existing column). The
# index uses the COSINE opclass (HNSW; needs pgvector >= 0.5.0) because the chosen
# model emits L2-normalised vectors. A btree on `corpus` speeds the scoped search.
_VECTOR_SCHEMA_SQL = f"""
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embeddings (
    corpus    text NOT NULL,
    entity_id text NOT NULL,
    text      text NOT NULL,
    source    text NOT NULL,
    tags      text[] NOT NULL DEFAULT '{{}}',
    embedding vector({int(settings.embeddings_dim)}) NOT NULL,
    PRIMARY KEY (corpus, entity_id)
);

CREATE INDEX IF NOT EXISTS embeddings_corpus_idx ON embeddings (corpus);
CREATE INDEX IF NOT EXISTS embeddings_vec_idx
    ON embeddings USING hnsw (embedding vector_cosine_ops);
"""


# --- Connection -------------------------------------------------------------


def _redacted_url(url: str) -> str:
    """Hide any password in the DB URL before it touches the logs."""
    # postgresql://user:password@host/db -> postgresql://user:***@host/db
    if "@" in url and "://" in url:
        scheme, rest = url.split("://", 1)
        creds, _, tail = rest.partition("@")
        if ":" in creds:
            user = creds.split(":", 1)[0]
            return f"{scheme}://{user}:***@{tail}"
    return url


@contextmanager
def connect() -> Iterator[psycopg.Connection]:
    """Yield a connection to `settings.database_url` as one transaction.

    Commits on clean exit, rolls back and logs loudly on any exception, and
    always closes. This is the single entry point for a unit of DB work.
    """
    safe_url = _redacted_url(settings.database_url)
    log.debug("db_connect", url=safe_url)
    conn = psycopg.connect(settings.database_url)
    try:
        yield conn
        conn.commit()
    except Exception as exc:
        conn.rollback()
        log.error("db_transaction_failed", url=safe_url, error=str(exc))
        raise
    finally:
        conn.close()


# --- Schema / reset ---------------------------------------------------------


def init_schema(conn: psycopg.Connection) -> None:
    """Create/upgrade the world schema if needed (idempotent).

    Runs the base schema (`CREATE ... IF NOT EXISTS`) then the additive migrations
    (`ALTER ... ADD COLUMN IF NOT EXISTS`), so an existing live DB is upgraded in
    place rather than wiped and rebuilt (OVERVIEW §2: migrations, not reseed).
    """
    log.info("db_init_schema")
    conn.execute(_SCHEMA_SQL)
    conn.execute(_MIGRATIONS_SQL)
    conn.execute(_VECTOR_SCHEMA_SQL)


def clear_world(conn: psycopg.Connection, *, scope: str = "world") -> None:
    """Empty world tables per `scope` so a re-seed reproduces the source state.

    Two scopes mirror the two seed commands (PHASE_D_OVERVIEW §2a), so a routine
    canon refresh never destroys the living world:

    * `scope="canon"` — the SAFE canon refresh (`make seed-canon`): wipe only the
      folder-owned tables (`canon`, `"cast"`) and the SEED events/stories, leaving
      tick-generated events + stories (the living world) untouched. TRUNCATE the
      fully-owned tables (orphan-free reload); a scoped DELETE for `source='seed'`
      events and stories. This is the load-bearing D3.0 guarantee: a bible edit +
      `seed-canon` leaves the living, tick-generated world standing.
    * `scope="world"` — the DESTRUCTIVE full wipe (`make reset-world`): TRUNCATE
      every world table (`canon`, `"cast"`, ALL events, ALL stories, `state`). It
      never touches the station config/catalog (grid/tracks/sponsors own their seeds).

    State is left to the caller's upserts under `scope="canon"` (so runtime/tick
    keys survive); the full wipe clears it.
    """
    if scope == "canon":
        log.info(
            "db_clear_world", scope=scope, tables="canon,cast,events+stories+emb[seed]"
        )
        conn.execute('TRUNCATE canon, "cast"')
        # Delete SEED beats first, then SEED stories (the FK is ON DELETE SET NULL, so
        # order isn't required for correctness, but this keeps the log orphan-free).
        conn.execute("DELETE FROM events WHERE source = %s", (EVENT_SOURCE_SEED,))
        conn.execute("DELETE FROM stories WHERE source = %s", (EVENT_SOURCE_SEED,))
        # Drop only the folder-derived (SEED) embeddings so the refresh re-embeds
        # them; TICK-sourced embeddings (D3/D10's living world) survive — mirrors
        # the events split above and the §2a "re-embedded affected rows" rule.
        conn.execute("DELETE FROM embeddings WHERE source = %s", (EVENT_SOURCE_SEED,))
    elif scope == "world":
        log.info("db_clear_world", scope=scope, tables=(*_WORLD_TABLES, "embeddings"))
        conn.execute(f"TRUNCATE {', '.join(_WORLD_TABLES)}")
        # embeddings is DERIVED — cleared wholesale on the destructive wipe, then
        # rebuilt by the re-seed (§2a: cleared + re-embedded on reset-world).
        conn.execute("TRUNCATE embeddings")
    else:
        raise ValueError(
            f"unknown clear_world scope {scope!r} (expected 'canon'|'world')"
        )


# --- Writes -----------------------------------------------------------------


def insert_canon(conn: psycopg.Connection, facts: Iterable[CanonFact]) -> int:
    """Insert canon facts; return how many rows were written."""
    rows = [(f.id, f.text, f.tags) for f in facts]
    conn.cursor().executemany(
        "INSERT INTO canon (id, text, tags) VALUES (%s, %s, %s)", rows
    )
    log.info("db_insert_canon", count=len(rows))
    return len(rows)


def insert_cast(conn: psycopg.Connection, members: Iterable[CastMember]) -> int:
    """Insert cast members; return how many rows were written."""
    rows = [(m.id, m.name, m.card_text, m.logical_voice, m.tags) for m in members]
    conn.cursor().executemany(
        'INSERT INTO "cast" (id, name, card_text, logical_voice, tags) '
        "VALUES (%s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_cast", count=len(rows))
    return len(rows)


# The full events column list + a single row->Event mapper, so every read returns
# the beat link (story_id/beat_kind, D3.0) without repeating the unpacking.
_EVENT_COLUMNS = (
    "id, title, body, in_world_datetime, status, tags, source, story_id, beat_kind"
)


def _event_from_row(row: tuple) -> Event:
    """Build an `Event` from a row selected with `_EVENT_COLUMNS`."""
    return Event(
        id=row[0],
        title=row[1],
        body=row[2],
        in_world_datetime=row[3],
        status=row[4],
        tags=list(row[5]),
        source=row[6],
        story_id=row[7],
        beat_kind=row[8],
    )


def insert_events(conn: psycopg.Connection, events: Iterable[Event]) -> int:
    """Insert events (carrying provenance + any story-beat link); return the count."""
    rows = [
        (
            e.id,
            e.title,
            e.body,
            e.in_world_datetime,
            e.status,
            e.tags,
            e.source,
            e.story_id,
            e.beat_kind,
        )
        for e in events
    ]
    conn.cursor().executemany(
        "INSERT INTO events "
        "(id, title, body, in_world_datetime, status, tags, source, story_id, "
        "beat_kind) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_events", count=len(rows))
    return len(rows)


def insert_beats(conn: psycopg.Connection, beats: Iterable[Event]) -> int:
    """Insert events that are story beats (each MUST carry a `story_id`); return count.

    A thin, intent-revealing wrapper over `insert_events`: a beat IS an event with a
    story link + an in-world datetime the clock already frames (D3.0 reuse). Validates
    the link is set so a tick bug can't write a dangling, unattributable beat.
    """
    beats = list(beats)
    missing = [b.id for b in beats if not b.story_id]
    if missing:
        raise ValueError(f"insert_beats: beats missing story_id: {missing}")
    return insert_events(conn, beats)


def insert_story(conn: psycopg.Connection, story: Story) -> None:
    """Insert one story-log row. `created_at` is left to the DB default (audit time)."""
    conn.execute(
        "INSERT INTO stories "
        "(id, title, summary, arc_stage, tags, source, created_tick, "
        "last_advanced_tick) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            story.id,
            story.title,
            story.summary,
            story.arc_stage,
            story.tags,
            story.source,
            story.created_tick,
            story.last_advanced_tick,
        ),
    )
    log.info("db_insert_story", id=story.id, arc_stage=story.arc_stage)


def advance_story(
    conn: psycopg.Connection,
    story_id: str,
    new_stage: str,
    *,
    tick: int | None = None,
) -> None:
    """Move a story to `new_stage` (validated forward-only) + stamp the advance tick.

    Reads the current stage, rejects an illegal/backward transition (and advancing a
    resolved `past` story) via `can_transition` — failing loudly rather than corrupting
    an arc. The new BEAT is written separately via `insert_beats` (a story's stage and
    its beats are distinct rows). `tick` is the advancing tick's counter; passing None
    leaves `last_advanced_tick` unchanged (COALESCE).
    """
    row = conn.execute(
        "SELECT arc_stage FROM stories WHERE id = %s", (story_id,)
    ).fetchone()
    if row is None:
        raise ValueError(f"advance_story: no story {story_id!r}")
    old_stage = row[0]
    if not can_transition(old_stage, new_stage):
        raise ValueError(
            f"advance_story: illegal arc transition {old_stage!r} -> {new_stage!r} "
            f"for story {story_id!r}"
        )
    conn.execute(
        "UPDATE stories SET arc_stage = %s, "
        "last_advanced_tick = COALESCE(%s, last_advanced_tick) WHERE id = %s",
        (new_stage, tick, story_id),
    )
    log.info(
        "db_advance_story",
        id=story_id,
        from_stage=old_stage,
        to_stage=new_stage,
        tick=tick,
    )


def set_state(conn: psycopg.Connection, key: str, value: str) -> None:
    """Upsert one key/value world-state row."""
    conn.execute(
        "INSERT INTO state (key, value) VALUES (%s, %s) "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
        (key, value),
    )
    log.debug("db_set_state", key=key)


# --- Embeddings (D2.1: the ONLY place vector SQL lives) ---------------------


def _vector_literal(vec: Sequence[float]) -> str:
    """Format a float vector as a pgvector text literal, e.g. ``[0.1,0.2,0.3]``.

    Bound as a plain text parameter and cast in SQL with ``%s::vector``, so this
    module needs NO pgvector Python adapter — the cast runs pgvector's own input
    function. ``repr(float(...))`` keeps full round-trip precision.
    """
    return "[" + ",".join(repr(float(x)) for x in vec) + "]"


def insert_embeddings(
    conn: psycopg.Connection, corpus: str, rows: Iterable[EmbeddingRow]
) -> int:
    """Upsert embedding rows for one `corpus`; return how many were written.

    Upsert (ON CONFLICT on the (corpus, entity_id) PK) so re-embedding an entity
    replaces it cleanly — a canon refresh can re-insert without a prior delete, and
    a half-finished embed run is safely re-runnable.
    """
    params = [
        (corpus, r.entity_id, r.text, r.source, r.tags, _vector_literal(r.embedding))
        for r in rows
    ]
    conn.cursor().executemany(
        "INSERT INTO embeddings (corpus, entity_id, text, source, tags, embedding) "
        "VALUES (%s, %s, %s, %s, %s, %s::vector) "
        "ON CONFLICT (corpus, entity_id) DO UPDATE SET "
        "text = EXCLUDED.text, source = EXCLUDED.source, "
        "tags = EXCLUDED.tags, embedding = EXCLUDED.embedding",
        params,
    )
    log.info("db_insert_embeddings", corpus=corpus, count=len(params))
    return len(params)


def delete_embeddings(
    conn: psycopg.Connection, corpus: str, entity_id: str | None = None
) -> int:
    """Delete embeddings for a `corpus` — one entity, or the whole corpus.

    `entity_id` set → remove that single soft-referenced row (call this when its
    backing entity is deleted, since no FK cascades across corpora — D10). `entity_id`
    None → clear the entire corpus (used to refresh a corpus on re-seed). Returns the
    row count deleted.
    """
    if entity_id is None:
        cur = conn.execute("DELETE FROM embeddings WHERE corpus = %s", (corpus,))
        n = cur.rowcount
        log.info("db_delete_embeddings", corpus=corpus, scope="corpus", count=n)
    else:
        cur = conn.execute(
            "DELETE FROM embeddings WHERE corpus = %s AND entity_id = %s",
            (corpus, entity_id),
        )
        n = cur.rowcount
        log.debug("db_delete_embeddings", corpus=corpus, entity_id=entity_id, count=n)
    return n


# --- Reads ------------------------------------------------------------------


def all_canon(conn: psycopg.Connection) -> list[CanonFact]:
    """All canon facts, ordered by id."""
    rows = conn.execute("SELECT id, text, tags FROM canon ORDER BY id").fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def canon_by_tags(conn: psycopg.Connection, tags: Iterable[str]) -> list[CanonFact]:
    """Canon facts whose tags overlap any of `tags`, ordered by id.

    The tag-matched retrieval B3's `context.assemble` uses to pull only the canon
    relevant to a topic. Uses Postgres array overlap (`&&`). An empty `tags` (or no
    overlap) returns no rows — the caller decides whether to fall back to the full
    set. NOTE: the seeded canon facts currently carry empty tags (the parser leaves
    them blank), so this returns nothing until facts are tagged; the seam is in
    place for when they are. Until then context.assemble falls back to `all_canon`.
    """
    tag_list = list(tags)
    log.debug("db_canon_by_tags", tags=tag_list)
    if not tag_list:
        return []
    rows = conn.execute(
        "SELECT id, text, tags FROM canon WHERE tags && %s ORDER BY id",
        (tag_list,),
    ).fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def canon_by_ids(conn: psycopg.Connection, ids: Iterable[str]) -> list[CanonFact]:
    """Canon facts for `ids`, returned in the SAME order as `ids` (rank-preserving).

    Used by `context._select_canon` to resolve semantic-search hits (entity ids,
    ranked by similarity) back to full `CanonFact` rows — keeping their meaning-rank
    order via `array_position`. Unknown ids are skipped (a lingering embedding for a
    deleted fact won't error). Empty `ids` returns no rows.
    """
    id_list = list(ids)
    if not id_list:
        return []
    rows = conn.execute(
        "SELECT id, text, tags FROM canon WHERE id = ANY(%s) "
        "ORDER BY array_position(%s, id)",
        (id_list, id_list),
    ).fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def all_cast(conn: psycopg.Connection) -> list[CastMember]:
    """All cast members, ordered by id."""
    rows = conn.execute(
        'SELECT id, name, card_text, logical_voice, tags FROM "cast" ORDER BY id'
    ).fetchall()
    return [
        CastMember(id, name, card, voice, list(tags))
        for id, name, card, voice, tags in rows
    ]


def get_cast_member(conn: psycopg.Connection, member_id: str) -> CastMember | None:
    """One cast member by id, or None."""
    row = conn.execute(
        'SELECT id, name, card_text, logical_voice, tags FROM "cast" WHERE id = %s',
        (member_id,),
    ).fetchone()
    if row is None:
        return None
    id, name, card, voice, tags = row
    return CastMember(id, name, card, voice, list(tags))


def get_event(conn: psycopg.Connection, event_id: str) -> Event | None:
    """One event by id, or None (used by the B2 progression demo)."""
    row = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events WHERE id = %s",
        (event_id,),
    ).fetchone()
    return None if row is None else _event_from_row(row)


def events_by_status(conn: psycopg.Connection, status: str) -> list[Event]:
    """Events with the given status, soonest first."""
    log.debug("db_events_by_status", status=status)
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events "
        "WHERE status = %s ORDER BY in_world_datetime",
        (status,),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


def events_in_range(
    conn: psycopg.Connection, start: datetime, end: datetime
) -> list[Event]:
    """Events whose in-world datetime falls within [start, end], soonest first.

    The date-window query B2/B3 use to find what is happening near `now`.
    """
    log.debug("db_events_in_range", start=start.isoformat(), end=end.isoformat())
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events "
        "WHERE in_world_datetime BETWEEN %s AND %s ORDER BY in_world_datetime",
        (start, end),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


# --- Story-log reads (D3.0: the news desk / tick read these) ----------------

_STORY_COLUMNS = (
    "id, title, summary, arc_stage, tags, source, "
    "created_tick, last_advanced_tick, created_at"
)


def _story_from_row(row: tuple) -> Story:
    """Build a `Story` from a row selected with `_STORY_COLUMNS`."""
    return Story(
        id=row[0],
        title=row[1],
        summary=row[2],
        arc_stage=row[3],
        tags=list(row[4]),
        source=row[5],
        created_tick=row[6],
        last_advanced_tick=row[7],
        created_at=row[8],
    )


def get_story(conn: psycopg.Connection, story_id: str) -> Story | None:
    """One story by id, or None."""
    row = conn.execute(
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE id = %s", (story_id,)
    ).fetchone()
    return None if row is None else _story_from_row(row)


def active_stories(
    conn: psycopg.Connection, *, limit: int | None = None
) -> list[Story]:
    """Unresolved stories (arc_stage != `past`), least-recently-advanced first.

    The set the tick draws from to advance (D3.2): ordering by `last_advanced_tick`
    (NULLS FIRST = never advanced) then birth spreads the tick's attention so old
    stories move on rather than starving. `limit` is the per-tick advance budget.
    """
    sql = (
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE arc_stage <> %s "
        "ORDER BY last_advanced_tick ASC NULLS FIRST, created_at ASC, id ASC"
    )
    params: tuple = (ARC_PAST,)
    if limit is not None:
        sql += " LIMIT %s"
        params = (ARC_PAST, limit)
    rows = conn.execute(sql, params).fetchall()
    return [_story_from_row(r) for r in rows]


def recent_stories(conn: psycopg.Connection, *, since_tick: int) -> list[Story]:
    """Stories created at or after `since_tick`, newest first — ANY arc stage.

    The recency window the world tick (D3.3) reads for domain balance + de-duplication:
    unlike `active_stories` it includes resolved (`past`) stories, because a festival
    that just resolved still means its domain was "busy" lately. Seeded example stories
    with a NULL `created_tick` are excluded (they predate the tick counter).
    """
    rows = conn.execute(
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE created_tick >= %s "
        "ORDER BY created_tick DESC, id",
        (since_tick,),
    ).fetchall()
    return [_story_from_row(r) for r in rows]


def story_beats(conn: psycopg.Connection, story_id: str) -> list[Event]:
    """All beats of a story (its linked events), in in-world chronological order.

    The arc as a timeline — what the news desk (D4) reads to narrate a story's
    development, each beat already clock-frameable by its `in_world_datetime`.
    """
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events WHERE story_id = %s "
        "ORDER BY in_world_datetime, id",
        (story_id,),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


def get_state(conn: psycopg.Connection, key: str) -> str | None:
    """One state value by key, or None."""
    row = conn.execute("SELECT value FROM state WHERE key = %s", (key,)).fetchone()
    return row[0] if row else None


def counts(conn: psycopg.Connection) -> dict[str, int]:
    """Row counts per world table — for seed verification and health checks."""
    out: dict[str, int] = {}
    for table in _WORLD_TABLES:
        n = conn.execute(f"SELECT count(*) FROM {table}").fetchone()[0]
        out[table.strip('"')] = n
    return out


def search(
    conn: psycopg.Connection,
    query_embedding: Sequence[float],
    *,
    corpus: str | None = None,
    k: int = 5,
) -> list[tuple[str, str, float]]:
    """Nearest embeddings to `query_embedding`, closest first — the vector read.

    `corpus=None` searches across ALL corpora (so D3/D4/D10 can recall over "canon +
    events + figures" at once); pass a corpus name to scope to one (D2's own use via
    `search_canon`). Returns ``(entity_id, text, score)`` where `score` is cosine
    similarity in ``[-1, 1]``, HIGHER = closer (matches the `Retrieved.score`
    contract) — derived as ``1 - <=>`` (pgvector's cosine *distance*). Ordering is by
    the distance operator so the HNSW cosine index is used.
    """
    qv = _vector_literal(query_embedding)
    log.debug("db_search", corpus=corpus or "*", k=k)
    if corpus is None:
        rows = conn.execute(
            "SELECT entity_id, text, 1 - (embedding <=> %s::vector) AS score "
            "FROM embeddings ORDER BY embedding <=> %s::vector LIMIT %s",
            (qv, qv, k),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT entity_id, text, 1 - (embedding <=> %s::vector) AS score "
            "FROM embeddings WHERE corpus = %s "
            "ORDER BY embedding <=> %s::vector LIMIT %s",
            (qv, corpus, qv, k),
        ).fetchall()
    return [(eid, text, float(score)) for eid, text, score in rows]


def search_canon(
    conn: psycopg.Connection, query_embedding: Sequence[float], *, k: int = 5
) -> list[tuple[str, str, float]]:
    """`search` scoped to the canon corpus — the convenience D2's `retrieve` calls."""
    return search(conn, query_embedding, corpus="canon", k=k)


def embeddings_count(conn: psycopg.Connection, *, corpus: str | None = None) -> int:
    """How many embeddings exist (optionally for one corpus) — seed verification."""
    if corpus is None:
        return conn.execute("SELECT count(*) FROM embeddings").fetchone()[0]
    return conn.execute(
        "SELECT count(*) FROM embeddings WHERE corpus = %s", (corpus,)
    ).fetchone()[0]
