"""The world-state store — the ONLY module that speaks SQL (Seam discipline).

Same rule as `providers/`: every database read/write goes through a function
here, and nothing outside this module imports `psycopg` or writes SQL. That keeps
the storage choice swappable (Postgres now; a managed DB or pgvector-enabled
instance later) and the query surface small and logged.

The schema is deliberately minimal but real (PHASE_B_TASKS.md B1):

    canon(id, text, tags)                           — the world's standing facts
    cast(id, name, card_text, logical_voice, tags)  — the DJs (note: "cast" is a
                                                       SQL keyword, always quoted)
    events(id, title, body, in_world_datetime, status, tags, source)
                                                    — dated occurrences; `source`
                                                       is seed (folder) | tick (D3)
    state(key, value)                               — small key/value world state

The canon bible (`docs/canon/`, formerly `docs/CANON.md`) stays the human-editable
source of truth; `world/seed.py` parses it (`world/canon_source.py`) and loads it
here. Connection details come from `settings.database_url` (B0.5) — never a
hardcoded string.

------------------------------------------------------------------------------
Vector search (LIVE as of D2.1; the seam this module reserved in B3 is now built):
pgvector is enabled in `init_schema` and the embeddings live in ONE polymorphic
table — `embeddings(corpus, entity_id, text, source, tags, embedding vector(N))`
— NOT a canon-only table, so D3 (events/stories) and D10 (figures/quotes) reuse it
by passing their own `corpus`. `N` is `settings.embeddings_dim`; the index uses the
COSINE opclass (the chosen model emits L2-normalised vectors). The embedding model
itself lives ONLY behind `providers/embeddings.py`; the vector SQL lives ONLY here
(`insert_embeddings`/`delete_embeddings`/`search`). `entity_id` is a *soft* cross-
table reference (a real FK can't span corpora), so per-entity cleanup is app logic
(`delete_embeddings`), not a cascade. The table is DERIVED/regenerable: re-embedded
on seed, cleared on `reset-world`, not backed up (§2a matrix).
------------------------------------------------------------------------------
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, timedelta

import psycopg

from ..config import settings
from ..logging_setup import get_logger

log = get_logger(__name__)


# --- Row shapes (1:1 with the tables) --------------------------------------
# Defined here because they mirror the schema this module owns; the parser
# (canon_source.py) and seed.py import them, so the row shape has one home.


@dataclass(frozen=True)
class CanonFact:
    """One standing world fact (a `canon` row)."""

    id: str
    text: str
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class CastMember:
    """One DJ / presenter (a `cast` row)."""

    id: str
    name: str
    card_text: str
    logical_voice: str
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Event:
    """One dated, progressing occurrence (an `events` row).

    `status` is a stored snapshot (upcoming/today/past) seeded from the bible; B2
    will (re)compute it from `in_world_datetime` relative to the world clock.

    `source` is the row's provenance (`seed` | `tick`): hand-authored from the canon
    folder vs generated by the nightly world tick (D3). It is what lets a canon
    refresh (`seed-canon`) replace only the seed events while the living, tick-
    generated world survives. Folder-loaded events default to `seed`.

    `story_id` + `beat_kind` (D3.0) make an event a *beat of a story*: a story is an
    arced sequence of these dated events (see `Story`). `story_id` is NULL for a
    standalone event (the seeded bible events, which aren't part of a generated arc);
    a tick beat carries its story's id. `beat_kind` is an optional, free-form tag for
    the kind of beat the tick authored it as (e.g. "rumour"/"announcement"/
    "development"/"consequence"/"resolution") — descriptive, not an enforced enum.
    Crucially a beat is STILL just an event with an `in_world_datetime`, so the B2
    clock frames it future/now/past for free — we reuse the events machinery, not
    duplicate it.
    """

    id: str
    title: str
    body: str
    in_world_datetime: datetime
    status: str
    tags: list[str] = field(default_factory=list)
    source: str = "seed"
    story_id: str | None = None
    beat_kind: str | None = None


# An event's provenance (the `events.source` column). A canon refresh replaces only
# SEED rows; TICK rows are the living world the world tick (D3) generates and must
# survive a re-seed. The same split is honoured by D3.0, D10.0 and the §2a matrix.
# The `embeddings.source` column (D2) reuses these SAME values: a canon refresh
# re-embeds the SEED-sourced rows and leaves TICK-sourced embeddings intact.
EVENT_SOURCE_SEED = "seed"
EVENT_SOURCE_TICK = "tick"

# Figures/quotes provenance (the `figures.source` / `quotes.source` column, D10.0).
# Mirrors the EVENT_SOURCE_* split, but the seed-side value is `bible` (these come from
# the hand-authored bible — see the §2a matrix, which names the folder-owned rows
# `source=bible`): a canon refresh re-seeds the BIBLE rows and leaves the TICK rows (the
# living world the tick generated) intact; a full reset clears both. The tick value is
# the SAME living-world marker as events, so the two stay in lockstep.
FIGURE_SOURCE_BIBLE = "bible"
FIGURE_SOURCE_TICK = EVENT_SOURCE_TICK  # "tick"

# The folder/hand-authored embedding sources a canon refresh re-embeds (and therefore
# drops first): seed events/canon AND bible figures/quotes. TICK-sourced embeddings (the
# living world) survive a refresh — §2a "re-embedded affected rows".
_FOLDER_EMBEDDING_SOURCES = (EVENT_SOURCE_SEED, FIGURE_SOURCE_BIBLE)


# --- Arc stages (D3.0: the narrative lifecycle of a story) ------------------
# Intrinsic domain data (not config — see the config-vs-constant rule in config.py),
# so it lives here next to the schema it governs. These are DISTINCT from
# `events.status_of`'s temporal upcoming/today/past, which is *derived* from a beat's
# datetime vs the world clock. The arc stage is a NARRATIVE property the tick authors
# and advances: a story can be temporally `past` (its latest beat is behind us) yet
# narratively still `developing` (consequences unfolding). Keep the two concepts
# separate — model arc stage explicitly here; derive temporal framing from the date.
ARC_RUMOURED = "rumoured"
ARC_UPCOMING = "upcoming"
ARC_HAPPENING = "happening"
ARC_DEVELOPING = "developing"
ARC_PAST = "past"

# The stages in forward order. `past` is terminal (a resolved story; the tick stops
# advancing it — D3.2 — but it stays in the log forever as history).
ARC_STAGES = (ARC_RUMOURED, ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST)

# Legal transitions: from a stage you may stay put (a new beat, same stage) or jump
# to ANY later stage (a sudden event can leap rumoured -> happening; a false rumour
# can resolve rumoured -> past) — but NEVER move backward, and `past` is terminal
# (no further beats). `advance_story` enforces this via `can_transition`.
ARC_TRANSITIONS: dict[str, tuple[str, ...]] = {
    ARC_RUMOURED: (ARC_RUMOURED, ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_UPCOMING: (ARC_UPCOMING, ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_HAPPENING: (ARC_HAPPENING, ARC_DEVELOPING, ARC_PAST),
    ARC_DEVELOPING: (ARC_DEVELOPING, ARC_PAST),
    ARC_PAST: (),
}


def is_resolved(arc_stage: str) -> bool:
    """True if a story's arc stage is terminal (`past`); the tick stops advancing it."""
    return arc_stage == ARC_PAST


def can_transition(old: str, new: str) -> bool:
    """Whether moving a story from arc stage `old` to `new` is legal (D3.0).

    Forward-or-same only; `past` is terminal. Raises on an unknown stage so a typo in
    the tick fails loudly rather than silently corrupting an arc.
    """
    for stage in (old, new):
        if stage not in ARC_STAGES:
            raise ValueError(
                f"unknown arc stage {stage!r}; expected one of {ARC_STAGES}"
            )
    return new in ARC_TRANSITIONS[old]


@dataclass(frozen=True)
class Story:
    """One arced story — a happening that progresses across ticks (a `stories` row).

    A story is the narrative spine; its individual dated developments are `events`
    rows linked by `story_id` (its *beats*), so each beat is clock-framed for free.
    `arc_stage` is one of `ARC_STAGES`. `source` reuses the EVENT_SOURCE_* split: the
    nightly tick writes `tick` (the living world, survives `seed-canon`); a seeded
    example story (D3.5) would be `seed` (replaced on a canon refresh). `created_tick`
    / `last_advanced_tick` are the monotonic tick counter (the tick owns it) for
    pacing — when the story was born and last moved. `created_at` is real wall-clock
    audit time, filled by the DB default on insert (read-only here).
    """

    id: str
    title: str
    summary: str
    arc_stage: str
    tags: list[str] = field(default_factory=list)
    source: str = EVENT_SOURCE_TICK
    created_tick: int | None = None
    last_advanced_tick: int | None = None
    created_at: datetime | None = None


@dataclass(frozen=True)
class NewsCoverage:
    """One record of the news desk covering a story in a bulletin (D4.0).

    The desk's *per-story coverage memory*: "how have I been telling this story?"
    One row per (story, bulletin) the desk airs — what arc stage it reported, the
    latest beat it reached (`last_beat_id`), and the short handle/angle it used, so
    successive bulletins can repeat, evolve (a new beat since `last_beat_id`), and
    name the story consistently (D4.1–D4.3).

    `covered_at` is the bulletin's IN-WORLD air time (a naive `timestamp`, the same
    timeline as `events.in_world_datetime`), so "since I last covered it" lines up
    with the story's beats rather than wall-clock. The caller passes it (the
    producer's `now`); it is NOT a DB default.

    DISTINCT from D5's anti-repetition memory: this is news-specific and per-story
    ("which stage/beat/angle did the desk reach on story X?"); D5 is broad,
    output-level freshness across ALL formats ("don't reuse this opening/phrasing").
    D5 layers on top of this — it does not duplicate it.

    `id` is the DB-assigned row id (read-only; ignored on insert).
    """

    story_id: str
    covered_at: datetime
    arc_stage: str
    last_beat_id: str | None = None
    angle: str = ""
    id: int | None = None


@dataclass(frozen=True)
class AirplayRecord:
    """One record of WHAT a generated segment aired — features only, never audio (D5.0).

    The station's broad, cross-format anti-repetition memory: per placed CONTENT
    segment, the salient features — a `topic`/beat handle, an `opening` fingerprint, and
    a few `features` (key phrases / structural beats) — so the writers' room can steer
    the next segment off recently-used ground (D5.2). Features only: the audio is GC'd
    by C2.5; this memory must OUTLIVE it.

    `aired_at` is the segment's BROADCAST air time — its pinned `air_time` on the
    scheduler's real timeline (a naive `timestamp`), NOT the in-world +600y clock that
    `events.in_world_datetime` / `news_coverage.covered_at` use. That is deliberate:
    anti-repetition is about BROADCAST adjacency (don't loop the same opening across
    back-to-back slots), so "recently on air" must line up with real air order, not with
    when the referenced events happen in-world. The caller passes it (the pinned
    `air_time`), and the freshness reads anchor on the same real `now`.

    DISTINCT from `NewsCoverage` (D4): that is news-specific and per-story — INTENDED
    recurrence (which story to re-report and how it evolves); this is broad and
    output-level — UNINTENDED repetition (don't reuse this opening/phrasing across ANY
    format). D5 layers on top of D4; it does not duplicate it.

    Runtime accrual, but PERSISTENT + BOUNDED: it survives a `seed-canon` refresh and
    the C2.5 audio prune, is bounded by `prune_airplay` (its OWN sweep, not the audio
    GC), and is cleared only by the destructive `reset-world` (§2a matrix). Static
    idents/evergreen/disclosure segments are NOT recorded (they are MEANT to repeat —
    the D5.1 chokepoint filters them).

    `id` is the DB-assigned row id (read-only; ignored on insert).
    """

    seg_id: str
    format: str
    aired_at: datetime
    topic: str | None = None
    opening: str | None = None
    features: list[str] = field(default_factory=list)
    id: int | None = None


@dataclass(frozen=True)
class Figure:
    """One invented in-world person — the people a story is *about* (a `figures` row).

    Distinct from a `CastMember` (the DJs/presenters): a figure is a world SUBJECT, not
    a host. `role` is their in-world title/role ("relay-keeper", "moon-president"),
    `card_text` a short bio the writers read. `voice_id` is OPTIONAL — set only when a
    figure is to be *voiced* as a soundbite/guest (D9); NULL otherwise (textual
    attribution needs no voice). `source` is the seed-vs-generated split
    (FIGURE_SOURCE_*): `bible` (hand-authored canon people) is re-seeded on a canon
    refresh; `tick` (generated by the world tick, D10.1) is the living world that
    SURVIVES a canon refresh.

    Musicians/artists are just figures with a music `role`/tag — which is what makes a
    song's artist a real, referenceable person in the world (D7's
    `tracks.artist_figure_id` links a track to its artist figure), not a text label.

    HARD RULE (CLAUDE.md IP boundary): invented people only — never a real person,
    public figure, or trademarked character.
    """

    id: str
    name: str
    role: str
    card_text: str
    voice_id: str | None = None
    tags: list[str] = field(default_factory=list)
    source: str = FIGURE_SOURCE_TICK


@dataclass(frozen=True)
class Quote:
    """One attributable statement — what a figure said (a `quotes` row, D10.0).

    Attached to a story (`story_id`) and optionally a specific beat (`beat_id`), so the
    news desk (D4) can attribute and quote it. Dated like a beat (`in_world_datetime`,
    the same naive `timestamp` timeline as `events`) so the B2 clock frames it
    future/now/past for free (`events.relative_phrase` — "said yesterday/today").
    `stance` is an optional free-form descriptor of the statement's tone/position
    ("defiant", "reassuring") — a hint for the writers/voice, NOT an enforced enum.
    `source` mirrors `Figure.source` (bible|tick): tick quotes are the living world and
    survive a canon refresh.
    """

    id: str
    story_id: str
    figure_id: str
    text: str
    in_world_datetime: datetime
    beat_id: str | None = None
    stance: str | None = None
    tags: list[str] = field(default_factory=list)
    source: str = FIGURE_SOURCE_TICK


@dataclass(frozen=True)
class Track:
    """One curated, playable song — a cultural artifact, not a labelled file (D7.0).

    A song in this world has an artist, an era, and a story; the DJ doesn't "play a
    piece of music," they say *"here's a classic from the 24th century, by …"*. The
    lore fields (`album`/`era`/`in_world_year`/`story_blurb`) are what the D7.4
    intro/back-announce + now-playing draw on.

    `in_world_artist` is the plain-text artist name (always set); `artist_figure_id`
    is the OPTIONAL link to a D10 `figures` row (the musician as a real in-world
    person). It is a SOFT reference, not a DB FK — deliberately: `tracks` is curated
    config/catalog that SURVIVES `reset-world` while `figures` is world state that
    gets truncated, so a hard FK would either block the wipe or cascade away curated
    rows. D7 ships with it null (text-only artists); D10 backfills it.

    `audio_path` is the repo-relative file the manifest names (the ONLY link between
    file and lore — nothing scans folders). A track is PLAYABLE iff that file exists
    on disk (checked live via `production.media.is_playable`, never a stored flag —
    dropping the file in makes the row playable without a re-seed). `duration_sec`
    is probed from the file at seed (`tts.probe_duration`) and stays NULL while the
    file is absent. `licence_note` is the human's clearance call (the manifest's
    `licence_default` fills it when a row doesn't override).

    Per the §2a matrix this is CURATED catalog, not world state: it survives
    `seed-canon` AND `reset-world`, refreshed only by its own `make seed-tracks`
    (source of truth: `config/tracks.yaml` — human-authored, diffable, in git).
    """

    id: str
    title: str
    in_world_artist: str
    mood: str
    audio_path: str
    artist_figure_id: str | None = None
    album: str | None = None
    era: str | None = None
    in_world_year: int | None = None
    story_blurb: str | None = None
    duration_sec: float | None = None
    licence_note: str | None = None
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Sponsor:
    """One REAL supporter acknowledged on air (a `sponsors` row, D8.2).

    Unlike everything else the station says, a sponsor is not fiction: it is a
    real person/outfit whose donation keeps the signal lit, acknowledged with a
    short **"Powered by {name}"** read (the wording rule is binding — always
    "Powered by," NEVER "Sponsored by"; `docs/MARKETING.md`). `powered_by_text`
    is the hand-entered blurb spoken AFTER the templated lead-in; `audio_path`
    is an OPTIONAL sponsor-supplied clip (repo-relative, under `assets/` so the
    C2.5 GC never touches it) played instead of a voiced read.

    The run window is REAL wall-clock time (operator-facing — when the support
    runs), checked by `active_sponsors(now)`: None `run_start` = already
    running, None `run_end` = open-ended. `weight` is the relative rotation
    share among concurrently active sponsors (the D8 placement cycles a
    weight-expanded list).

    Per the §2a matrix this is HAND-ENTERED catalog, not world state: it
    survives `seed-canon` AND `reset-world`, refreshed only by its own
    `make seed-sponsors` (source of truth: `config/sponsors.yaml`). The table
    ships EMPTY — populating real sponsors is gated on CM (donations live),
    not on D8.
    """

    id: str
    name: str
    powered_by_text: str
    audio_path: str | None = None
    run_start: datetime | None = None
    run_end: datetime | None = None
    weight: int = 1
    tags: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class EmbeddingRow:
    """One row to write into the polymorphic `embeddings` table (D2).

    `corpus` is NOT a field — it is the per-batch argument to `insert_embeddings`
    (every row in a batch shares one corpus, e.g. "canon"). `source` is the same
    seed/tick provenance as `events.source` (see EVENT_SOURCE_*). `embedding` is the
    N-float vector; its length MUST equal `settings.embeddings_dim` (the producer
    behind `providers/embeddings.py` validates that — a wrong-dim insert will also
    fail loudly against the `vector(N)` column).
    """

    entity_id: str
    text: str
    source: str
    embedding: list[float]
    tags: list[str] = field(default_factory=list)


# --- Schema -----------------------------------------------------------------

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS canon (
    id   text PRIMARY KEY,
    text text NOT NULL,
    tags text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS "cast" (
    id            text PRIMARY KEY,
    name          text NOT NULL,
    card_text     text NOT NULL,
    logical_voice text NOT NULL,
    tags          text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS events (
    id                text PRIMARY KEY,
    title             text NOT NULL,
    body              text NOT NULL,
    in_world_datetime timestamp NOT NULL,
    status            text NOT NULL,
    tags              text[] NOT NULL DEFAULT '{}',
    source            text NOT NULL DEFAULT 'seed'
);

-- The story log (D3.0): arced happenings the nightly tick generates + advances. The
-- beats themselves are `events` rows linked back via `events.story_id` (added in the
-- migrations below) — reuse, not a separate beats table. `source` reuses the
-- seed/tick split (see EVENT_SOURCE_*): tick-owned stories survive a `seed-canon`.
CREATE TABLE IF NOT EXISTS stories (
    id                 text PRIMARY KEY,
    title              text NOT NULL,
    summary            text NOT NULL,
    arc_stage          text NOT NULL,
    tags               text[] NOT NULL DEFAULT '{}',
    source             text NOT NULL DEFAULT 'tick',
    created_tick       integer,
    last_advanced_tick integer,
    created_at         timestamptz NOT NULL DEFAULT now()
);

-- The news desk's per-story coverage memory (D4.0): one row per (story, bulletin)
-- the desk aired — what stage + latest beat it reported and the angle/handle it used,
-- so bulletins can repeat / evolve / stay consistent (D4.1–D4.3). `covered_at` is the
-- bulletin's in-world air time (same naive `timestamp` timeline as the beats). Runtime
-- accrual: it survives a `seed-canon` refresh and is cleared on `reset-world` (§2a).
-- `story_id` CASCADEs (no orphan coverage if a seed story is replaced); a removed beat
-- nulls `last_beat_id` rather than deleting the coverage. DISTINCT from D5's broad
-- anti-repetition memory (see the NewsCoverage docstring) — D5 layers on, not dupes.
CREATE TABLE IF NOT EXISTS news_coverage (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    story_id     text NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    covered_at   timestamp NOT NULL,
    arc_stage    text NOT NULL,
    last_beat_id text REFERENCES events(id) ON DELETE SET NULL,
    angle        text NOT NULL DEFAULT ''
);

-- The on-air anti-repetition memory (D5.0): one row per placed CONTENT segment — its
-- salient features (a topic/beat handle, an opening fingerprint, a few key phrases),
-- NOT the audio — so the writers' room (D5.2) can avoid looping the same beat / opening
-- / phrasing across 24/7 output. `aired_at` is the segment's BROADCAST air time (its
-- pinned real-timeline `air_time`, NOT the in-world clock — anti-repetition is about
-- real air adjacency; see the AirplayRecord docstring). Runtime accrual, but
-- PERSISTENT + BOUNDED: it survives a `seed-canon` refresh AND the C2.5 audio prune
-- (the point — it must outlive the audio), is bounded by `prune_airplay` (its OWN
-- sweep), and is cleared only on `reset-world` (it is in `_WORLD_TABLES`). DISTINCT
-- from `news_coverage` (D4): that is per-story INTENDED recurrence; this is broad
-- output-phrasing freshness (see the AirplayRecord docstring). No FK to a segment — the
-- audio is GC'd, this memory deliberately is not.
CREATE TABLE IF NOT EXISTS airplay_history (
    id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    seg_id   text NOT NULL,
    format   text NOT NULL,
    aired_at timestamp NOT NULL,
    topic    text,
    opening  text,
    features text[] NOT NULL DEFAULT '{}'
);

-- The world's invented PEOPLE (D10.0): the figures a story is *about* — officials,
-- artists, witnesses, musicians. Distinct from the `cast` (the DJs/presenters): a
-- figure is a world SUBJECT, not a host. `role` is their in-world title/role,
-- `card_text` a short bio, `voice_id` OPTIONAL (set only to *voice* a figure — D9).
-- `source` is the seed-vs-generated split (FIGURE_SOURCE_*): `bible` (hand-authored
-- canon people, re-seeded by seed-canon) vs `tick` (generated by the tick, survives a
-- canon refresh — §2a). HARD RULE: invented people only, never a real/trademarked one.
CREATE TABLE IF NOT EXISTS figures (
    id        text PRIMARY KEY,
    name      text NOT NULL,
    role      text NOT NULL,
    card_text text NOT NULL,
    voice_id  text,
    tags      text[] NOT NULL DEFAULT '{}',
    source    text NOT NULL DEFAULT 'tick'
);

-- Attributable STATEMENTS (D10.0): what a figure said, attached to a story (and
-- optionally one beat). Dated like a beat (`in_world_datetime`, same naive `timestamp`
-- timeline as events) so the B2 clock frames it (said yesterday/today) for free.
-- `stance` is an optional free-form tone/position descriptor, NOT an enum. `source`
-- mirrors `figures.source` (bible|tick). FKs: a quote dies with its story (CASCADE),
-- loses its beat link if that beat is removed (SET NULL), and dies with its figure
-- (CASCADE). `figures` must exist before this table (the inline REFERENCES) — it does,
-- just above.
CREATE TABLE IF NOT EXISTS quotes (
    id                text PRIMARY KEY,
    story_id          text NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
    beat_id           text REFERENCES events(id) ON DELETE SET NULL,
    figure_id         text NOT NULL REFERENCES figures(id) ON DELETE CASCADE,
    text              text NOT NULL,
    in_world_datetime timestamp NOT NULL,
    stance            text,
    tags              text[] NOT NULL DEFAULT '{}',
    source            text NOT NULL DEFAULT 'tick'
);

CREATE TABLE IF NOT EXISTS state (
    key   text PRIMARY KEY,
    value text NOT NULL
);

-- Indexes for the structured event retrieval B2/B3 lean on (by status, by date).
CREATE INDEX IF NOT EXISTS events_status_idx   ON events (status);
CREATE INDEX IF NOT EXISTS events_datetime_idx ON events (in_world_datetime);
CREATE INDEX IF NOT EXISTS stories_stage_idx   ON stories (arc_stage);
CREATE INDEX IF NOT EXISTS stories_source_idx  ON stories (source);
-- The desk reads coverage by story, newest first (`last_coverage`).
CREATE INDEX IF NOT EXISTS news_coverage_story_idx
    ON news_coverage (story_id, covered_at DESC);
-- D5.0: the freshness reads pull the recent window newest-first, all formats or one.
CREATE INDEX IF NOT EXISTS airplay_aired_idx ON airplay_history (aired_at DESC);
CREATE INDEX IF NOT EXISTS airplay_format_aired_idx
    ON airplay_history (format, aired_at DESC);
-- Figures/quotes (D10.0): the canon refresh deletes by `source`; the desk/tick read
-- quotes by story, by figure, and by date window.
CREATE INDEX IF NOT EXISTS figures_source_idx  ON figures (source);
CREATE INDEX IF NOT EXISTS quotes_story_idx     ON quotes (story_id);
CREATE INDEX IF NOT EXISTS quotes_figure_idx    ON quotes (figure_id);
CREATE INDEX IF NOT EXISTS quotes_datetime_idx  ON quotes (in_world_datetime);
CREATE INDEX IF NOT EXISTS quotes_source_idx    ON quotes (source);
"""

# Additive, idempotent migrations applied on every `init_schema`, AFTER the schema
# above. This is how a schema change lands once the world is alive: never a
# truncate-reseed (OVERVIEW §2), always `ADD COLUMN IF NOT EXISTS` / a backfill that
# is safe to run repeatedly. On a fresh DB these are no-ops (the column already
# exists from CREATE); on an existing DB they upgrade it in place. The source index
# lives here (not in the schema) so it is only built after the column is guaranteed.
_MIGRATIONS_SQL = """
ALTER TABLE events ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'seed';
CREATE INDEX IF NOT EXISTS events_source_idx ON events (source);

-- D3.0: link an event to its story as a beat (NULL = a standalone, non-arc event).
-- The FK runs `ON DELETE SET NULL` so deleting a story (a full reset) never orphan-
-- errors; the inline REFERENCES needs `stories` to exist first, which the base
-- schema above guarantees (it runs before these migrations). `beat_kind` is an
-- optional free-form descriptor of the beat (see Event docstring).
ALTER TABLE events ADD COLUMN IF NOT EXISTS story_id text
    REFERENCES stories(id) ON DELETE SET NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS beat_kind text;
CREATE INDEX IF NOT EXISTS events_story_idx ON events (story_id);
"""

# The world tables, in a stable order for a single TRUNCATE that reproduces the world
# cleanly on a full reset. The FKs criss-cross (events→stories; news_coverage→both;
# quotes→stories/events/figures), but all truncate in one statement so each
# referenced table goes with its referrers. `news_coverage` (D4.0) and `airplay_history`
# (D5.0) are runtime accrual, not source-of-truth world state, but BOTH are cleared on
# the destructive `reset-world` (§2a) and counted — so they live here. (They are NOT in
# the `scope="canon"` refresh, so a bible edit leaves them standing — §2a: "survives".)
# `embeddings` is handled separately (it is DERIVED, regenerable — see below).
# `tracks` (D7.0) is deliberately ABSENT: it is curated config/catalog (§2a), owned
# by `make seed-tracks`, and survives even the destructive full wipe.
_WORLD_TABLES = (
    "canon",
    '"cast"',
    "events",
    "stories",
    "figures",
    "quotes",
    "news_coverage",
    "airplay_history",
    "state",
)

# --- Vector schema (D2.1: pgvector + the ONE polymorphic embeddings table) ---
# Run in init_schema AFTER the base schema. `CREATE EXTENSION vector` needs the
# pgvector system package installed (README documents the Homebrew step) and fails
# LOUDLY if it isn't — the right behaviour, not a silent skip. The table is multi-
# corpus from day one so D3/D10 reuse it (corpus ∈ canon now; event/story/figure/
# quote later). `vector(N)` interpolates `settings.embeddings_dim` (cast to int —
# config, never user input); a later model change means a re-embed + a column
# migration (this CREATE ... IF NOT EXISTS won't resize an existing column). The
# index uses the COSINE opclass (HNSW; needs pgvector >= 0.5.0) because the chosen
# model emits L2-normalised vectors. A btree on `corpus` speeds the scoped search.
_VECTOR_SCHEMA_SQL = f"""
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embeddings (
    corpus    text NOT NULL,
    entity_id text NOT NULL,
    text      text NOT NULL,
    source    text NOT NULL,
    tags      text[] NOT NULL DEFAULT '{{}}',
    embedding vector({int(settings.embeddings_dim)}) NOT NULL,
    PRIMARY KEY (corpus, entity_id)
);

CREATE INDEX IF NOT EXISTS embeddings_corpus_idx ON embeddings (corpus);
CREATE INDEX IF NOT EXISTS embeddings_vec_idx
    ON embeddings USING hnsw (embedding vector_cosine_ops);
"""

# --- Catalog schema (D7.0: the curated tracks catalogue) ---------------------
# CURATED CONFIG/CATALOG, not world state (§2a): deliberately NOT in
# `_WORLD_TABLES`, so it survives both `seed-canon` and the destructive
# `reset-world`; it is cleared/refreshed only by its own `make seed-tracks`
# (source of truth: config/tracks.yaml). `artist_figure_id` is a SOFT reference
# to `figures` (no FK — see the Track docstring: tracks outlive a world wipe that
# truncates figures; D10 backfills the link). No extra indexes: a curated
# catalogue is dozens of rows, the PK is plenty.
_CATALOG_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS tracks (
    id               text PRIMARY KEY,
    title            text NOT NULL,
    in_world_artist  text NOT NULL,
    artist_figure_id text,
    album            text,
    era              text,
    in_world_year    integer,
    mood             text NOT NULL,
    story_blurb      text,
    duration_sec     real,
    licence_note     text,
    audio_path       text NOT NULL,
    tags             text[] NOT NULL DEFAULT '{}'
);

-- D8.2: real supporters acknowledged with "Powered by" reads. HAND-ENTERED
-- catalog like tracks (§2a): outside _WORLD_TABLES, survives seed-canon AND
-- reset-world, owned by `make seed-sponsors` (config/sponsors.yaml). Run
-- window is REAL wall-clock time; NULLs mean already-running / open-ended.
-- Ships empty — real sponsors are populated at CM (donations live).
CREATE TABLE IF NOT EXISTS sponsors (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    powered_by_text text NOT NULL,
    audio_path      text,
    run_start       timestamp,
    run_end         timestamp,
    weight          integer NOT NULL DEFAULT 1,
    tags            text[] NOT NULL DEFAULT '{}'
);
"""


# --- Connection -------------------------------------------------------------


def _redacted_url(url: str) -> str:
    """Hide any password in the DB URL before it touches the logs."""
    # postgresql://user:password@host/db -> postgresql://user:***@host/db
    if "@" in url and "://" in url:
        scheme, rest = url.split("://", 1)
        creds, _, tail = rest.partition("@")
        if ":" in creds:
            user = creds.split(":", 1)[0]
            return f"{scheme}://{user}:***@{tail}"
    return url


@contextmanager
def connect() -> Iterator[psycopg.Connection]:
    """Yield a connection to `settings.database_url` as one transaction.

    Commits on clean exit, rolls back and logs loudly on any exception, and
    always closes. This is the single entry point for a unit of DB work.
    """
    safe_url = _redacted_url(settings.database_url)
    log.debug("db_connect", url=safe_url)
    conn = psycopg.connect(settings.database_url)
    try:
        yield conn
        conn.commit()
    except Exception as exc:
        conn.rollback()
        log.error("db_transaction_failed", url=safe_url, error=str(exc))
        raise
    finally:
        conn.close()


# --- Schema / reset ---------------------------------------------------------


def init_schema(conn: psycopg.Connection) -> None:
    """Create/upgrade the world schema if needed (idempotent).

    Runs the base schema (`CREATE ... IF NOT EXISTS`) then the additive migrations
    (`ALTER ... ADD COLUMN IF NOT EXISTS`), so an existing live DB is upgraded in
    place rather than wiped and rebuilt (OVERVIEW §2: migrations, not reseed).
    """
    log.info("db_init_schema")
    conn.execute(_SCHEMA_SQL)
    conn.execute(_MIGRATIONS_SQL)
    conn.execute(_VECTOR_SCHEMA_SQL)
    conn.execute(_CATALOG_SCHEMA_SQL)


def clear_world(conn: psycopg.Connection, *, scope: str = "world") -> None:
    """Empty world tables per `scope` so a re-seed reproduces the source state.

    Two scopes mirror the two seed commands (PHASE_D_OVERVIEW §2a), so a routine
    canon refresh never destroys the living world:

    * `scope="canon"` — the SAFE canon refresh (`make seed-canon`): wipe only the
      folder-owned tables (`canon`, `"cast"`) and the SEED events/stories, leaving
      tick-generated events + stories (the living world) untouched. TRUNCATE the
      fully-owned tables (orphan-free reload); a scoped DELETE for `source='seed'`
      events and stories. This is the load-bearing D3.0 guarantee: a bible edit +
      `seed-canon` leaves the living, tick-generated world standing.
    * `scope="world"` — the DESTRUCTIVE full wipe (`make reset-world`): TRUNCATE
      every world table (`canon`, `"cast"`, ALL events, ALL stories, `state`). It
      never touches the station config/catalog (grid/tracks/sponsors own their seeds).

    State is left to the caller's upserts under `scope="canon"` (so runtime/tick
    keys survive); the full wipe clears it.
    """
    if scope == "canon":
        log.info(
            "db_clear_world",
            scope=scope,
            tables="canon,cast,events+stories+figures+quotes+emb[folder]",
        )
        conn.execute('TRUNCATE canon, "cast"')
        # Delete the folder-authored rows by their seed-side `source` marker, leaving
        # the living, tick-generated world standing. BIBLE quotes before BIBLE figures
        # so a bible figure's removal doesn't cascade-orphan a quote mid-refresh (the FK
        # is CASCADE, so order isn't required for correctness, but keeps the log clean).
        conn.execute("DELETE FROM quotes WHERE source = %s", (FIGURE_SOURCE_BIBLE,))
        conn.execute("DELETE FROM figures WHERE source = %s", (FIGURE_SOURCE_BIBLE,))
        # Delete SEED beats first, then SEED stories (the FK is ON DELETE SET NULL, so
        # order isn't required for correctness, but this keeps the log orphan-free).
        conn.execute("DELETE FROM events WHERE source = %s", (EVENT_SOURCE_SEED,))
        conn.execute("DELETE FROM stories WHERE source = %s", (EVENT_SOURCE_SEED,))
        # Drop only the folder-derived embeddings (SEED events/canon + BIBLE
        # figures/quotes) so the refresh re-embeds them; TICK-sourced embeddings (the
        # living world) survive — mirrors the splits above and the §2a "re-embedded
        # affected rows" rule.
        conn.execute(
            "DELETE FROM embeddings WHERE source = ANY(%s)",
            (list(_FOLDER_EMBEDDING_SOURCES),),
        )
    elif scope == "world":
        log.info("db_clear_world", scope=scope, tables=(*_WORLD_TABLES, "embeddings"))
        conn.execute(f"TRUNCATE {', '.join(_WORLD_TABLES)}")
        # embeddings is DERIVED — cleared wholesale on the destructive wipe, then
        # rebuilt by the re-seed (§2a: cleared + re-embedded on reset-world).
        conn.execute("TRUNCATE embeddings")
    else:
        raise ValueError(
            f"unknown clear_world scope {scope!r} (expected 'canon'|'world')"
        )


# --- Writes -----------------------------------------------------------------


def insert_canon(conn: psycopg.Connection, facts: Iterable[CanonFact]) -> int:
    """Insert canon facts; return how many rows were written."""
    rows = [(f.id, f.text, f.tags) for f in facts]
    conn.cursor().executemany(
        "INSERT INTO canon (id, text, tags) VALUES (%s, %s, %s)", rows
    )
    log.info("db_insert_canon", count=len(rows))
    return len(rows)


def insert_cast(conn: psycopg.Connection, members: Iterable[CastMember]) -> int:
    """Insert cast members; return how many rows were written."""
    rows = [(m.id, m.name, m.card_text, m.logical_voice, m.tags) for m in members]
    conn.cursor().executemany(
        'INSERT INTO "cast" (id, name, card_text, logical_voice, tags) '
        "VALUES (%s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_cast", count=len(rows))
    return len(rows)


# The full events column list + a single row->Event mapper, so every read returns
# the beat link (story_id/beat_kind, D3.0) without repeating the unpacking.
_EVENT_COLUMNS = (
    "id, title, body, in_world_datetime, status, tags, source, story_id, beat_kind"
)


def _event_from_row(row: tuple) -> Event:
    """Build an `Event` from a row selected with `_EVENT_COLUMNS`."""
    return Event(
        id=row[0],
        title=row[1],
        body=row[2],
        in_world_datetime=row[3],
        status=row[4],
        tags=list(row[5]),
        source=row[6],
        story_id=row[7],
        beat_kind=row[8],
    )


def insert_events(conn: psycopg.Connection, events: Iterable[Event]) -> int:
    """Insert events (carrying provenance + any story-beat link); return the count."""
    rows = [
        (
            e.id,
            e.title,
            e.body,
            e.in_world_datetime,
            e.status,
            e.tags,
            e.source,
            e.story_id,
            e.beat_kind,
        )
        for e in events
    ]
    conn.cursor().executemany(
        "INSERT INTO events "
        "(id, title, body, in_world_datetime, status, tags, source, story_id, "
        "beat_kind) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_events", count=len(rows))
    return len(rows)


def insert_beats(conn: psycopg.Connection, beats: Iterable[Event]) -> int:
    """Insert events that are story beats (each MUST carry a `story_id`); return count.

    A thin, intent-revealing wrapper over `insert_events`: a beat IS an event with a
    story link + an in-world datetime the clock already frames (D3.0 reuse). Validates
    the link is set so a tick bug can't write a dangling, unattributable beat.
    """
    beats = list(beats)
    missing = [b.id for b in beats if not b.story_id]
    if missing:
        raise ValueError(f"insert_beats: beats missing story_id: {missing}")
    return insert_events(conn, beats)


def insert_story(conn: psycopg.Connection, story: Story) -> None:
    """Insert one story-log row. `created_at` is left to the DB default (audit time)."""
    conn.execute(
        "INSERT INTO stories "
        "(id, title, summary, arc_stage, tags, source, created_tick, "
        "last_advanced_tick) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        (
            story.id,
            story.title,
            story.summary,
            story.arc_stage,
            story.tags,
            story.source,
            story.created_tick,
            story.last_advanced_tick,
        ),
    )
    log.info("db_insert_story", id=story.id, arc_stage=story.arc_stage)


def advance_story(
    conn: psycopg.Connection,
    story_id: str,
    new_stage: str,
    *,
    tick: int | None = None,
) -> None:
    """Move a story to `new_stage` (validated forward-only) + stamp the advance tick.

    Reads the current stage, rejects an illegal/backward transition (and advancing a
    resolved `past` story) via `can_transition` — failing loudly rather than corrupting
    an arc. The new BEAT is written separately via `insert_beats` (a story's stage and
    its beats are distinct rows). `tick` is the advancing tick's counter; passing None
    leaves `last_advanced_tick` unchanged (COALESCE).
    """
    row = conn.execute(
        "SELECT arc_stage FROM stories WHERE id = %s", (story_id,)
    ).fetchone()
    if row is None:
        raise ValueError(f"advance_story: no story {story_id!r}")
    old_stage = row[0]
    if not can_transition(old_stage, new_stage):
        raise ValueError(
            f"advance_story: illegal arc transition {old_stage!r} -> {new_stage!r} "
            f"for story {story_id!r}"
        )
    conn.execute(
        "UPDATE stories SET arc_stage = %s, "
        "last_advanced_tick = COALESCE(%s, last_advanced_tick) WHERE id = %s",
        (new_stage, tick, story_id),
    )
    log.info(
        "db_advance_story",
        id=story_id,
        from_stage=old_stage,
        to_stage=new_stage,
        tick=tick,
    )


def insert_figures(conn: psycopg.Connection, figures: Iterable[Figure]) -> int:
    """Insert invented in-world people (figures); return how many rows were written.

    Carries `source` (bible|tick) so the canon refresh can keep tick-generated figures.
    `voice_id` is NULL unless the figure is to be voiced (D9).
    """
    rows = [
        (f.id, f.name, f.role, f.card_text, f.voice_id, f.tags, f.source)
        for f in figures
    ]
    conn.cursor().executemany(
        "INSERT INTO figures (id, name, role, card_text, voice_id, tags, source) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_figures", count=len(rows))
    return len(rows)


def insert_quotes(conn: psycopg.Connection, quotes: Iterable[Quote]) -> int:
    """Insert attributable statements (quotes), each linked to a story + figure; count.

    A quote is dated (`in_world_datetime`) like a beat so the clock frames it; `beat_id`
    optionally pins it to a specific beat. `story_id`/`figure_id` are NOT NULL (the DB
    FKs enforce the links), so a dangling, unattributable quote can't be written.
    """
    rows = [
        (
            q.id,
            q.story_id,
            q.beat_id,
            q.figure_id,
            q.text,
            q.in_world_datetime,
            q.stance,
            q.tags,
            q.source,
        )
        for q in quotes
    ]
    conn.cursor().executemany(
        "INSERT INTO quotes (id, story_id, beat_id, figure_id, text, "
        "in_world_datetime, stance, tags, source) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_quotes", count=len(rows))
    return len(rows)


def clear_tracks(conn: psycopg.Connection) -> None:
    """Empty the curated tracks catalogue so `seed-tracks` reproduces the manifest.

    ONLY the tracks seeder calls this (the catalogue's own refresh path — §2a);
    it is never part of `clear_world`, in either scope.
    """
    log.info("db_clear_tracks")
    conn.execute("TRUNCATE tracks")


def insert_tracks(conn: psycopg.Connection, tracks: Iterable[Track]) -> int:
    """Insert curated tracks (the music-lore catalogue, D7.0); return the count."""
    rows = [
        (
            t.id,
            t.title,
            t.in_world_artist,
            t.artist_figure_id,
            t.album,
            t.era,
            t.in_world_year,
            t.mood,
            t.story_blurb,
            t.duration_sec,
            t.licence_note,
            t.audio_path,
            t.tags,
        )
        for t in tracks
    ]
    conn.cursor().executemany(
        "INSERT INTO tracks (id, title, in_world_artist, artist_figure_id, album, "
        "era, in_world_year, mood, story_blurb, duration_sec, licence_note, "
        "audio_path, tags) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_tracks", count=len(rows))
    return len(rows)


def clear_sponsors(conn: psycopg.Connection) -> None:
    """Empty the sponsors catalog so `seed-sponsors` reproduces the manifest.

    ONLY the sponsors seeder calls this (the catalog's own refresh path — §2a);
    `clear_world` never touches it, in either scope.
    """
    log.info("db_clear_sponsors")
    conn.execute("TRUNCATE sponsors")


def insert_sponsors(conn: psycopg.Connection, sponsors: Iterable[Sponsor]) -> int:
    """Insert sponsors (the hand-entered supporter catalog, D8.2); return the count."""
    rows = [
        (
            s.id,
            s.name,
            s.powered_by_text,
            s.audio_path,
            s.run_start,
            s.run_end,
            s.weight,
            s.tags,
        )
        for s in sponsors
    ]
    conn.cursor().executemany(
        "INSERT INTO sponsors (id, name, powered_by_text, audio_path, run_start, "
        "run_end, weight, tags) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        rows,
    )
    log.info("db_insert_sponsors", count=len(rows))
    return len(rows)


def set_state(conn: psycopg.Connection, key: str, value: str) -> None:
    """Upsert one key/value world-state row."""
    conn.execute(
        "INSERT INTO state (key, value) VALUES (%s, %s) "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
        (key, value),
    )
    log.debug("db_set_state", key=key)


def record_coverage(conn: psycopg.Connection, coverage: NewsCoverage) -> None:
    """Record that a bulletin covered a story (D4.0). `id` is DB-assigned (ignored).

    Append-only: each call adds a row, building the per-story coverage history the
    desk reads back via `last_coverage` / `coverage_since`. The caller supplies
    `covered_at` (the bulletin's in-world air time); `last_beat_id` may be NULL when
    a story is covered without a concrete beat yet (e.g. a rumour with no event row).
    """
    conn.execute(
        "INSERT INTO news_coverage (story_id, covered_at, arc_stage, last_beat_id, "
        "angle) VALUES (%s, %s, %s, %s, %s)",
        (
            coverage.story_id,
            coverage.covered_at,
            coverage.arc_stage,
            coverage.last_beat_id,
            coverage.angle,
        ),
    )
    log.info(
        "db_record_coverage",
        story_id=coverage.story_id,
        arc_stage=coverage.arc_stage,
        last_beat_id=coverage.last_beat_id,
    )


def record_airplay(conn: psycopg.Connection, record: AirplayRecord) -> None:
    """Record a placed segment's salient features in the airplay memory (D5.0).

    Append-only: one row per CONTENT segment, written at the scheduler chokepoint
    (D5.1, next to `_write_sidecar`). `id` is DB-assigned (ignored). `aired_at` is the
    segment's in-world air time (the caller passes the pinned slot `air_time`). Static
    idents/evergreen/disclosure segments are NOT recorded — the caller filters them
    (they are MEANT to repeat). DISTINCT from `record_coverage` (D4, per-story
    recurrence): this is the broad output-phrasing freshness memory (see AirplayRecord).
    """
    conn.execute(
        "INSERT INTO airplay_history (seg_id, format, aired_at, topic, opening, "
        "features) VALUES (%s, %s, %s, %s, %s, %s)",
        (
            record.seg_id,
            record.format,
            record.aired_at,
            record.topic,
            record.opening,
            record.features,
        ),
    )
    log.info(
        "db_record_airplay",
        seg_id=record.seg_id,
        format=record.format,
        topic=record.topic,
    )


def prune_airplay(conn: psycopg.Connection, now: datetime, *, keep: timedelta) -> int:
    """Drop airplay rows older than `keep` before in-world `now`; return rows removed.

    The bound that keeps a 24/7 station's airplay memory from growing forever (D5.0).
    `keep` is the retention window (the freshness window × a margin — see
    `settings.freshness_retention_margin`), wide enough that `recent_airplay` never
    misses a row. This is the airplay memory's OWN sweep — deliberately NOT the C2.5
    audio `prune` (that GCs files; this memory must OUTLIVE the audio). Folded into the
    scheduler housekeeping at the chokepoint (D5.1).
    """
    cutoff = now - keep
    cur = conn.execute("DELETE FROM airplay_history WHERE aired_at < %s", (cutoff,))
    n = cur.rowcount
    log.info("db_prune_airplay", removed=n, cutoff=cutoff.isoformat())
    return n


# --- Embeddings (D2.1: the ONLY place vector SQL lives) ---------------------


def _vector_literal(vec: Sequence[float]) -> str:
    """Format a float vector as a pgvector text literal, e.g. ``[0.1,0.2,0.3]``.

    Bound as a plain text parameter and cast in SQL with ``%s::vector``, so this
    module needs NO pgvector Python adapter — the cast runs pgvector's own input
    function. ``repr(float(...))`` keeps full round-trip precision.
    """
    return "[" + ",".join(repr(float(x)) for x in vec) + "]"


def insert_embeddings(
    conn: psycopg.Connection, corpus: str, rows: Iterable[EmbeddingRow]
) -> int:
    """Upsert embedding rows for one `corpus`; return how many were written.

    Upsert (ON CONFLICT on the (corpus, entity_id) PK) so re-embedding an entity
    replaces it cleanly — a canon refresh can re-insert without a prior delete, and
    a half-finished embed run is safely re-runnable.
    """
    params = [
        (corpus, r.entity_id, r.text, r.source, r.tags, _vector_literal(r.embedding))
        for r in rows
    ]
    conn.cursor().executemany(
        "INSERT INTO embeddings (corpus, entity_id, text, source, tags, embedding) "
        "VALUES (%s, %s, %s, %s, %s, %s::vector) "
        "ON CONFLICT (corpus, entity_id) DO UPDATE SET "
        "text = EXCLUDED.text, source = EXCLUDED.source, "
        "tags = EXCLUDED.tags, embedding = EXCLUDED.embedding",
        params,
    )
    log.info("db_insert_embeddings", corpus=corpus, count=len(params))
    return len(params)


def delete_embeddings(
    conn: psycopg.Connection, corpus: str, entity_id: str | None = None
) -> int:
    """Delete embeddings for a `corpus` — one entity, or the whole corpus.

    `entity_id` set → remove that single soft-referenced row (call this when its
    backing entity is deleted, since no FK cascades across corpora — D10). `entity_id`
    None → clear the entire corpus (used to refresh a corpus on re-seed). Returns the
    row count deleted.
    """
    if entity_id is None:
        cur = conn.execute("DELETE FROM embeddings WHERE corpus = %s", (corpus,))
        n = cur.rowcount
        log.info("db_delete_embeddings", corpus=corpus, scope="corpus", count=n)
    else:
        cur = conn.execute(
            "DELETE FROM embeddings WHERE corpus = %s AND entity_id = %s",
            (corpus, entity_id),
        )
        n = cur.rowcount
        log.debug("db_delete_embeddings", corpus=corpus, entity_id=entity_id, count=n)
    return n


# --- Reads ------------------------------------------------------------------


def all_canon(conn: psycopg.Connection) -> list[CanonFact]:
    """All canon facts, ordered by id."""
    rows = conn.execute("SELECT id, text, tags FROM canon ORDER BY id").fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def canon_by_tags(conn: psycopg.Connection, tags: Iterable[str]) -> list[CanonFact]:
    """Canon facts whose tags overlap any of `tags`, ordered by id.

    The tag-matched retrieval B3's `context.assemble` uses to pull only the canon
    relevant to a topic. Uses Postgres array overlap (`&&`). An empty `tags` (or no
    overlap) returns no rows — the caller decides whether to fall back to the full
    set. NOTE: the seeded canon facts currently carry empty tags (the parser leaves
    them blank), so this returns nothing until facts are tagged; the seam is in
    place for when they are. Until then context.assemble falls back to `all_canon`.
    """
    tag_list = list(tags)
    log.debug("db_canon_by_tags", tags=tag_list)
    if not tag_list:
        return []
    rows = conn.execute(
        "SELECT id, text, tags FROM canon WHERE tags && %s ORDER BY id",
        (tag_list,),
    ).fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def canon_by_ids(conn: psycopg.Connection, ids: Iterable[str]) -> list[CanonFact]:
    """Canon facts for `ids`, returned in the SAME order as `ids` (rank-preserving).

    Used by `context._select_canon` to resolve semantic-search hits (entity ids,
    ranked by similarity) back to full `CanonFact` rows — keeping their meaning-rank
    order via `array_position`. Unknown ids are skipped (a lingering embedding for a
    deleted fact won't error). Empty `ids` returns no rows.
    """
    id_list = list(ids)
    if not id_list:
        return []
    rows = conn.execute(
        "SELECT id, text, tags FROM canon WHERE id = ANY(%s) "
        "ORDER BY array_position(%s, id)",
        (id_list, id_list),
    ).fetchall()
    return [CanonFact(id, text, list(tags)) for id, text, tags in rows]


def all_cast(conn: psycopg.Connection) -> list[CastMember]:
    """All cast members, ordered by id."""
    rows = conn.execute(
        'SELECT id, name, card_text, logical_voice, tags FROM "cast" ORDER BY id'
    ).fetchall()
    return [
        CastMember(id, name, card, voice, list(tags))
        for id, name, card, voice, tags in rows
    ]


def get_cast_member(conn: psycopg.Connection, member_id: str) -> CastMember | None:
    """One cast member by id, or None."""
    row = conn.execute(
        'SELECT id, name, card_text, logical_voice, tags FROM "cast" WHERE id = %s',
        (member_id,),
    ).fetchone()
    if row is None:
        return None
    id, name, card, voice, tags = row
    return CastMember(id, name, card, voice, list(tags))


def get_event(conn: psycopg.Connection, event_id: str) -> Event | None:
    """One event by id, or None (used by the B2 progression demo)."""
    row = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events WHERE id = %s",
        (event_id,),
    ).fetchone()
    return None if row is None else _event_from_row(row)


def events_by_status(conn: psycopg.Connection, status: str) -> list[Event]:
    """Events with the given status, soonest first."""
    log.debug("db_events_by_status", status=status)
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events "
        "WHERE status = %s ORDER BY in_world_datetime",
        (status,),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


def events_in_range(
    conn: psycopg.Connection, start: datetime, end: datetime
) -> list[Event]:
    """Events whose in-world datetime falls within [start, end], soonest first.

    The date-window query B2/B3 use to find what is happening near `now`.
    """
    log.debug("db_events_in_range", start=start.isoformat(), end=end.isoformat())
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events "
        "WHERE in_world_datetime BETWEEN %s AND %s ORDER BY in_world_datetime",
        (start, end),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


# --- Story-log reads (D3.0: the news desk / tick read these) ----------------

_STORY_COLUMNS = (
    "id, title, summary, arc_stage, tags, source, "
    "created_tick, last_advanced_tick, created_at"
)


def _story_from_row(row: tuple) -> Story:
    """Build a `Story` from a row selected with `_STORY_COLUMNS`."""
    return Story(
        id=row[0],
        title=row[1],
        summary=row[2],
        arc_stage=row[3],
        tags=list(row[4]),
        source=row[5],
        created_tick=row[6],
        last_advanced_tick=row[7],
        created_at=row[8],
    )


def get_story(conn: psycopg.Connection, story_id: str) -> Story | None:
    """One story by id, or None."""
    row = conn.execute(
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE id = %s", (story_id,)
    ).fetchone()
    return None if row is None else _story_from_row(row)


def active_stories(
    conn: psycopg.Connection, *, limit: int | None = None
) -> list[Story]:
    """Unresolved stories (arc_stage != `past`), least-recently-advanced first.

    The set the tick draws from to advance (D3.2): ordering by `last_advanced_tick`
    (NULLS FIRST = never advanced) then birth spreads the tick's attention so old
    stories move on rather than starving. `limit` is the per-tick advance budget.
    """
    sql = (
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE arc_stage <> %s "
        "ORDER BY last_advanced_tick ASC NULLS FIRST, created_at ASC, id ASC"
    )
    params: tuple = (ARC_PAST,)
    if limit is not None:
        sql += " LIMIT %s"
        params = (ARC_PAST, limit)
    rows = conn.execute(sql, params).fetchall()
    return [_story_from_row(r) for r in rows]


def recent_stories(conn: psycopg.Connection, *, since_tick: int) -> list[Story]:
    """Stories created at or after `since_tick`, newest first — ANY arc stage.

    The recency window the world tick (D3.3) reads for domain balance + de-duplication:
    unlike `active_stories` it includes resolved (`past`) stories, because a festival
    that just resolved still means its domain was "busy" lately. Seeded example stories
    with a NULL `created_tick` are excluded (they predate the tick counter).
    """
    rows = conn.execute(
        f"SELECT {_STORY_COLUMNS} FROM stories WHERE created_tick >= %s "
        "ORDER BY created_tick DESC, id",
        (since_tick,),
    ).fetchall()
    return [_story_from_row(r) for r in rows]


def story_beats(conn: psycopg.Connection, story_id: str) -> list[Event]:
    """All beats of a story (its linked events), in in-world chronological order.

    The arc as a timeline — what the news desk (D4) reads to narrate a story's
    development, each beat already clock-frameable by its `in_world_datetime`.
    """
    rows = conn.execute(
        f"SELECT {_EVENT_COLUMNS} FROM events WHERE story_id = %s "
        "ORDER BY in_world_datetime, id",
        (story_id,),
    ).fetchall()
    return [_event_from_row(r) for r in rows]


# --- Figures & quotes reads (D10.0: the news desk / writers read these) -----

_FIGURE_COLUMNS = "id, name, role, card_text, voice_id, tags, source"
_QUOTE_COLUMNS = (
    "id, story_id, beat_id, figure_id, text, in_world_datetime, stance, tags, source"
)


def _figure_from_row(row: tuple) -> Figure:
    """Build a `Figure` from a row selected with `_FIGURE_COLUMNS`."""
    return Figure(
        id=row[0],
        name=row[1],
        role=row[2],
        card_text=row[3],
        voice_id=row[4],
        tags=list(row[5]),
        source=row[6],
    )


def _quote_from_row(row: tuple) -> Quote:
    """Build a `Quote` from a row selected with `_QUOTE_COLUMNS`."""
    return Quote(
        id=row[0],
        story_id=row[1],
        beat_id=row[2],
        figure_id=row[3],
        text=row[4],
        in_world_datetime=row[5],
        stance=row[6],
        tags=list(row[7]),
        source=row[8],
    )


def get_figure(conn: psycopg.Connection, figure_id: str) -> Figure | None:
    """One figure by id, or None."""
    row = conn.execute(
        f"SELECT {_FIGURE_COLUMNS} FROM figures WHERE id = %s", (figure_id,)
    ).fetchone()
    return None if row is None else _figure_from_row(row)


def figures_for_story(conn: psycopg.Connection, story_id: str) -> list[Figure]:
    """The invented people involved in a story — those it quotes — ordered by id.

    Figures link to a story THROUGH their quotes (there is no `figures.story_id`): a
    figure is "in" a story when they have a statement in it, so the news desk (D4) can
    list whom to attribute. DISTINCT so a figure quoted across beats appears once.
    """
    rows = conn.execute(
        f"SELECT DISTINCT {', '.join('f.' + c for c in _FIGURE_COLUMNS.split(', '))} "
        "FROM figures f JOIN quotes q ON q.figure_id = f.id "
        "WHERE q.story_id = %s ORDER BY f.id",
        (story_id,),
    ).fetchall()
    return [_figure_from_row(r) for r in rows]


def quotes_for_story(conn: psycopg.Connection, story_id: str) -> list[Quote]:
    """All quotes attached to a story, in in-world chronological order (oldest first).

    The story's statements as a timeline — what the news desk reads to attribute and
    quote, each already clock-frameable by its `in_world_datetime`.
    """
    rows = conn.execute(
        f"SELECT {_QUOTE_COLUMNS} FROM quotes WHERE story_id = %s "
        "ORDER BY in_world_datetime, id",
        (story_id,),
    ).fetchall()
    return [_quote_from_row(r) for r in rows]


def quotes_near(
    conn: psycopg.Connection, start: datetime, end: datetime
) -> list[Quote]:
    """Quotes whose in-world datetime falls within [start, end], soonest first.

    The date-window read (parallel to `events_in_range`) for "what was said around now"
    — the news desk pulling recent statements regardless of which story they belong to.
    """
    rows = conn.execute(
        f"SELECT {_QUOTE_COLUMNS} FROM quotes "
        "WHERE in_world_datetime BETWEEN %s AND %s ORDER BY in_world_datetime, id",
        (start, end),
    ).fetchall()
    return [_quote_from_row(r) for r in rows]


def attributed_quotes_for_story(
    conn: psycopg.Connection, story_id: str, *, limit: int | None = None
) -> list[tuple[Quote, Figure]]:
    """A story's quotes paired with their speaking figure, NEWEST first (D10.2).

    One JOIN so the news desk / writers' room can attribute ("X, the relay-keeper,
    said …") without a second per-quote read. Newest first (the most recent statement
    leads), and `limit` caps how many a brief carries — a story needs a couple of
    voices, not all. Each quote keeps its own in-world datetime for temporal framing
    (`events.phrase_for_datetime`).
    """
    q_cols = ", ".join("q." + c for c in _QUOTE_COLUMNS.split(", "))
    f_cols = ", ".join("f." + c for c in _FIGURE_COLUMNS.split(", "))
    sql = (
        f"SELECT {q_cols}, {f_cols} FROM quotes q JOIN figures f ON f.id = q.figure_id "
        "WHERE q.story_id = %s ORDER BY q.in_world_datetime DESC, q.id DESC"
    )
    params: tuple = (story_id,)
    if limit is not None:
        sql += " LIMIT %s"
        params = (story_id, limit)
    rows = conn.execute(sql, params).fetchall()
    n = len(_QUOTE_COLUMNS.split(", "))
    return [(_quote_from_row(r[:n]), _figure_from_row(r[n:])) for r in rows]


def attributed_quotes_near(
    conn: psycopg.Connection,
    start: datetime,
    end: datetime,
    *,
    limit: int | None = None,
) -> list[tuple[Quote, Figure]]:
    """Quotes in [start, end] paired with their figure, NEWEST first (D10.2).

    The structured "what was said around now" read the writers' room uses when no topic
    is in play (the date-window analog of `attributed_quotes_for_story`). `limit` bounds
    how many reach the prompt.
    """
    q_cols = ", ".join("q." + c for c in _QUOTE_COLUMNS.split(", "))
    f_cols = ", ".join("f." + c for c in _FIGURE_COLUMNS.split(", "))
    sql = (
        f"SELECT {q_cols}, {f_cols} FROM quotes q JOIN figures f ON f.id = q.figure_id "
        "WHERE q.in_world_datetime BETWEEN %s AND %s "
        "ORDER BY q.in_world_datetime DESC, q.id DESC"
    )
    params: tuple = (start, end)
    if limit is not None:
        sql += " LIMIT %s"
        params = (start, end, limit)
    rows = conn.execute(sql, params).fetchall()
    n = len(_QUOTE_COLUMNS.split(", "))
    return [(_quote_from_row(r[:n]), _figure_from_row(r[n:])) for r in rows]


def attributed_quotes_by_ids(
    conn: psycopg.Connection, ids: Iterable[str]
) -> list[tuple[Quote, Figure]]:
    """Quotes for `ids` paired with their figure, in the SAME order as `ids` (D10.2).

    Resolves semantic-recall hits (quote ids ranked by meaning, `embeddings.retrieve`
    over the `quote` corpus) back to full rows with their speaker, preserving the
    meaning-rank via `array_position`. Unknown ids skipped; empty `ids` returns none.
    """
    id_list = list(ids)
    if not id_list:
        return []
    q_cols = ", ".join("q." + c for c in _QUOTE_COLUMNS.split(", "))
    f_cols = ", ".join("f." + c for c in _FIGURE_COLUMNS.split(", "))
    rows = conn.execute(
        f"SELECT {q_cols}, {f_cols} FROM quotes q JOIN figures f ON f.id = q.figure_id "
        "WHERE q.id = ANY(%s) ORDER BY array_position(%s, q.id)",
        (id_list, id_list),
    ).fetchall()
    n = len(_QUOTE_COLUMNS.split(", "))
    return [(_quote_from_row(r[:n]), _figure_from_row(r[n:])) for r in rows]


# --- Tracks catalogue reads (D7.0: the music selector / DJ intro read these) --

_TRACK_COLUMNS = (
    "id, title, in_world_artist, artist_figure_id, album, era, in_world_year, "
    "mood, story_blurb, duration_sec, licence_note, audio_path, tags"
)


def _track_from_row(row: tuple) -> Track:
    """Build a `Track` from a row selected with `_TRACK_COLUMNS`."""
    return Track(
        id=row[0],
        title=row[1],
        in_world_artist=row[2],
        artist_figure_id=row[3],
        album=row[4],
        era=row[5],
        in_world_year=row[6],
        mood=row[7],
        story_blurb=row[8],
        duration_sec=row[9],
        licence_note=row[10],
        audio_path=row[11],
        tags=list(row[12]),
    )


def get_track(conn: psycopg.Connection, track_id: str) -> Track | None:
    """One track by id, or None."""
    row = conn.execute(
        f"SELECT {_TRACK_COLUMNS} FROM tracks WHERE id = %s", (track_id,)
    ).fetchone()
    return None if row is None else _track_from_row(row)


def all_tracks(conn: psycopg.Connection) -> list[Track]:
    """The whole curated catalogue, ordered by id.

    Playability (the file exists on disk) is NOT a column — filter with
    `production.media.is_playable` (the file is the only link, checked live).
    """
    rows = conn.execute(f"SELECT {_TRACK_COLUMNS} FROM tracks ORDER BY id").fetchall()
    return [_track_from_row(r) for r in rows]


def tracks_by_mood(conn: psycopg.Connection, mood: str) -> list[Track]:
    """Tracks with the given mood, ordered by id (a D7.4 selector input)."""
    rows = conn.execute(
        f"SELECT {_TRACK_COLUMNS} FROM tracks WHERE mood = %s ORDER BY id",
        (mood,),
    ).fetchall()
    return [_track_from_row(r) for r in rows]


def tracks_by_tags(conn: psycopg.Connection, tags: Iterable[str]) -> list[Track]:
    """Tracks whose tags overlap any of `tags`, ordered by id (array overlap `&&`).

    Empty `tags` returns no rows — same contract as `canon_by_tags`.
    """
    tag_list = list(tags)
    if not tag_list:
        return []
    rows = conn.execute(
        f"SELECT {_TRACK_COLUMNS} FROM tracks WHERE tags && %s ORDER BY id",
        (tag_list,),
    ).fetchall()
    return [_track_from_row(r) for r in rows]


# --- Sponsors catalog reads (D8.2: the "Powered by" read placement) -----------

_SPONSOR_COLUMNS = (
    "id, name, powered_by_text, audio_path, run_start, run_end, weight, tags"
)


def _sponsor_from_row(row: tuple) -> Sponsor:
    """Build a `Sponsor` from a row selected with `_SPONSOR_COLUMNS`."""
    return Sponsor(
        id=row[0],
        name=row[1],
        powered_by_text=row[2],
        audio_path=row[3],
        run_start=row[4],
        run_end=row[5],
        weight=row[6],
        tags=list(row[7]),
    )


def active_sponsors(conn: psycopg.Connection, now: datetime) -> list[Sponsor]:
    """Sponsors whose run window contains `now` (REAL wall clock), ordered by id.

    The window is half-open `[run_start, run_end)`; a NULL start means already
    running, a NULL end open-ended. An empty table (pre-CM: no donations yet)
    returns nothing — and the placement airs no reads. This is THE read the D8
    sponsor placement uses; nothing ever reads an out-of-window sponsor.
    """
    rows = conn.execute(
        f"SELECT {_SPONSOR_COLUMNS} FROM sponsors "
        "WHERE (run_start IS NULL OR run_start <= %s) "
        "AND (run_end IS NULL OR %s < run_end) ORDER BY id",
        (now, now),
    ).fetchall()
    return [_sponsor_from_row(r) for r in rows]


def all_sponsors(conn: psycopg.Connection) -> list[Sponsor]:
    """The whole sponsors catalog, ordered by id (operator/console visibility)."""
    rows = conn.execute(
        f"SELECT {_SPONSOR_COLUMNS} FROM sponsors ORDER BY id"
    ).fetchall()
    return [_sponsor_from_row(r) for r in rows]


def tracks_by_artist(conn: psycopg.Connection, artist: str) -> list[Track]:
    """Tracks by an artist's plain-text name, ordered by id.

    Matches `in_world_artist` (the always-set text name). Once D10 backfills
    `artist_figure_id`, a figure-keyed read can join properly; until then the
    name is the artist's identity (the manifest keeps it consistent per roster).
    """
    rows = conn.execute(
        f"SELECT {_TRACK_COLUMNS} FROM tracks WHERE in_world_artist = %s ORDER BY id",
        (artist,),
    ).fetchall()
    return [_track_from_row(r) for r in rows]


# --- News coverage reads (D4.0: the desk reads its own history) -------------

_COVERAGE_COLUMNS = "id, story_id, covered_at, arc_stage, last_beat_id, angle"


def _coverage_from_row(row: tuple) -> NewsCoverage:
    """Build a `NewsCoverage` from a row selected with `_COVERAGE_COLUMNS`."""
    return NewsCoverage(
        id=row[0],
        story_id=row[1],
        covered_at=row[2],
        arc_stage=row[3],
        last_beat_id=row[4],
        angle=row[5],
    )


def last_coverage(conn: psycopg.Connection, story_id: str) -> NewsCoverage | None:
    """The most recent coverage of a story, or None if never covered (D4.0).

    "How did I last tell this story?" — the stage/beat/angle the desk reached, so the
    next bulletin can decide repeat vs evolve (a beat newer than `last_beat_id`) and
    reuse consistent naming (D4.1–D4.3). Newest by in-world `covered_at`, then `id` to
    break ties within one bulletin time.
    """
    row = conn.execute(
        f"SELECT {_COVERAGE_COLUMNS} FROM news_coverage WHERE story_id = %s "
        "ORDER BY covered_at DESC, id DESC LIMIT 1",
        (story_id,),
    ).fetchone()
    return None if row is None else _coverage_from_row(row)


def coverage_since(conn: psycopg.Connection, t: datetime) -> list[NewsCoverage]:
    """All coverage rows aired at or after in-world time `t`, newest first (D4.0).

    The recent-coverage window the desk reads to balance the hour (what it has already
    aired lately, across all stories), e.g. since the previous bulletin's `now`.
    """
    rows = conn.execute(
        f"SELECT {_COVERAGE_COLUMNS} FROM news_coverage WHERE covered_at >= %s "
        "ORDER BY covered_at DESC, id DESC",
        (t,),
    ).fetchall()
    return [_coverage_from_row(r) for r in rows]


# --- Airplay history reads (D5.0: the writers' room reads its own recent output) ---

_AIRPLAY_COLUMNS = "id, seg_id, format, aired_at, topic, opening, features"


def _airplay_from_row(row: tuple) -> AirplayRecord:
    """Build an `AirplayRecord` from a row selected with `_AIRPLAY_COLUMNS`."""
    return AirplayRecord(
        id=row[0],
        seg_id=row[1],
        format=row[2],
        aired_at=row[3],
        topic=row[4],
        opening=row[5],
        features=list(row[6]),
    )


def recent_airplay(
    conn: psycopg.Connection,
    now: datetime,
    *,
    within: timedelta,
    limit: int | None = None,
) -> list[AirplayRecord]:
    """Airplay records within `within` of broadcast `now`, newest first (D5.0).

    The recency window the writers' room reads (D5.2) to avoid looping — across ALL
    formats. `now` is the real broadcast time (the slot's `air_time`), the same timeline
    `aired_at` is stored on. The window is anchored at `now` (`aired_at >= now -
    within`) with NO upper bound, because the upcoming buffer holds segments placed
    AHEAD of `now`: with `within` above `buffer_depth_hours` (freshness_window_hours)
    the whole buffer counts as "recent", which is exactly what we want to steer the next
    segment off. `limit` caps how many rows return (newest first). Degrades to an empty
    list on a cold start (no rows yet) — callers must handle that.
    """
    sql = (
        f"SELECT {_AIRPLAY_COLUMNS} FROM airplay_history WHERE aired_at >= %s "
        "ORDER BY aired_at DESC, id DESC"
    )
    params: tuple = (now - within,)
    if limit is not None:
        sql += " LIMIT %s"
        params = (now - within, limit)
    rows = conn.execute(sql, params).fetchall()
    return [_airplay_from_row(r) for r in rows]


def recent_by_format(
    conn: psycopg.Connection,
    now: datetime,
    fmt: str,
    *,
    within: timedelta,
    limit: int | None = None,
) -> list[AirplayRecord]:
    """`recent_airplay` scoped to one `format` (e.g. just `talk` or `news`), D5.0.

    The format-specific read: a producer can avoid reusing openings within its OWN
    format without being constrained by another format's wording. Same window semantics
    as `recent_airplay`.
    """
    sql = (
        f"SELECT {_AIRPLAY_COLUMNS} FROM airplay_history "
        "WHERE format = %s AND aired_at >= %s ORDER BY aired_at DESC, id DESC"
    )
    params: tuple = (fmt, now - within)
    if limit is not None:
        sql += " LIMIT %s"
        params = (fmt, now - within, limit)
    rows = conn.execute(sql, params).fetchall()
    return [_airplay_from_row(r) for r in rows]


def get_state(conn: psycopg.Connection, key: str) -> str | None:
    """One state value by key, or None."""
    row = conn.execute("SELECT value FROM state WHERE key = %s", (key,)).fetchone()
    return row[0] if row else None


def counts(conn: psycopg.Connection) -> dict[str, int]:
    """Row counts per world table — for seed verification and health checks.

    The catalog tables (`tracks`, `sponsors` — §2a hand-entered, outside the
    world wipes) are counted too, for the same visibility, without being part
    of `_WORLD_TABLES` (they must never join a world TRUNCATE).
    """
    out: dict[str, int] = {}
    for table in (*_WORLD_TABLES, "tracks", "sponsors"):
        n = conn.execute(f"SELECT count(*) FROM {table}").fetchone()[0]
        out[table.strip('"')] = n
    return out


def search(
    conn: psycopg.Connection,
    query_embedding: Sequence[float],
    *,
    corpus: str | None = None,
    k: int = 5,
) -> list[tuple[str, str, float]]:
    """Nearest embeddings to `query_embedding`, closest first — the vector read.

    `corpus=None` searches across ALL corpora (so D3/D4/D10 can recall over "canon +
    events + figures" at once); pass a corpus name to scope to one (D2's own use via
    `search_canon`). Returns ``(entity_id, text, score)`` where `score` is cosine
    similarity in ``[-1, 1]``, HIGHER = closer (matches the `Retrieved.score`
    contract) — derived as ``1 - <=>`` (pgvector's cosine *distance*). Ordering is by
    the distance operator so the HNSW cosine index is used.
    """
    qv = _vector_literal(query_embedding)
    log.debug("db_search", corpus=corpus or "*", k=k)
    if corpus is None:
        rows = conn.execute(
            "SELECT entity_id, text, 1 - (embedding <=> %s::vector) AS score "
            "FROM embeddings ORDER BY embedding <=> %s::vector LIMIT %s",
            (qv, qv, k),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT entity_id, text, 1 - (embedding <=> %s::vector) AS score "
            "FROM embeddings WHERE corpus = %s "
            "ORDER BY embedding <=> %s::vector LIMIT %s",
            (qv, corpus, qv, k),
        ).fetchall()
    return [(eid, text, float(score)) for eid, text, score in rows]


def search_canon(
    conn: psycopg.Connection, query_embedding: Sequence[float], *, k: int = 5
) -> list[tuple[str, str, float]]:
    """`search` scoped to the canon corpus — the convenience D2's `retrieve` calls."""
    return search(conn, query_embedding, corpus="canon", k=k)


def embeddings_count(conn: psycopg.Connection, *, corpus: str | None = None) -> int:
    """How many embeddings exist (optionally for one corpus) — seed verification."""
    if corpus is None:
        return conn.execute("SELECT count(*) FROM embeddings").fetchone()[0]
    return conn.execute(
        "SELECT count(*) FROM embeddings WHERE corpus = %s", (corpus,)
    ).fetchone()[0]
